import json
def make(i,title,rows,ex):
 items=[]
 for w,r,ro,m,p,e,er,eo,tr,u,n in rows: items.append({'word':w,'reading':r,'romaji':ro,'meaning':m,'pos':p,'usage':u,'example':e,'example_reading':er,'example_romaji':eo,'translation':tr,'nuance':n})
 json.dump({'id':i,'title':title,'overview':'Practical N3 vocabulary with contextual examples.','items':items,'exercises':ex},open(f'content/vocab_{i}.json','w',encoding='utf8'),ensure_ascii=False,indent=2)
make(26,'Quantities and comparison',[
('数量','すうりょう','suuryou','quantity','noun','注文の数量を確認した。','ちゅうもんのすうりょうをかくにんした。','Chuumon no suuryou o kakunin shita.','I checked the quantity in the order.','数量を確認する','数量 is a measured amount of items.'),('割合','わりあい','wariai','ratio; percentage','noun','学生の割合が増えている。','がくせいのわりあいがふえている。','Gakusei no wariai ga fuete iru.','The proportion of students is increasing.','割合が高い','割合 expresses a proportion or percentage.'),('平均','へいきん','heikin','average','noun/suru verb','今月の平均気温を調べた。','こんげつのへいきんきおんをしらべた。','Kongetsu no heikin kion o shirabeta.','I looked up this month’s average temperature.','平均気温','平均 is the statistical average.'),('最大','さいだい','saidai','maximum','noun/な-adjective','最大三人まで入室できます。','さいだいさんにんまではいしつできます。','Saidai sannin made nyuushitsu dekimasu.','Up to three people may enter.','最大三人','最大 indicates the upper limit.'),('最小','さいしょう','saishou','minimum','noun/な-adjective','最小サイズを選んだ。','さいしょうさいずをえらんだ。','Saishou saizu o eranda.','I chose the smallest size.','最小限','最小 indicates the lower limit.'),('増減','ぞうげん','zougen','increase or decrease','noun/suru verb','価格の増減を毎月記録する。','かかくのぞうげんをまいつききろくする。','Kakaku no zougen o maitsuki kiroku suru.','We record price increases and decreases each month.','増減を記録する','増減 covers either an increase or a decrease.')],[{'type':'meaning','question':'What does 平均 mean?','options':['average','maximum','quantity'],'answer':'average','explanation':'平均 means average.'},{'type':'reading','question':'Reading of 数量?','options':['すうりょう','すりょう','かずりょう'],'answer':'すうりょう','explanation':'数量 is read すうりょう.'},{'type':'translation','question':'Translate: 最小サイズを選んだ。','answer':'I chose the smallest size.','explanation':'最小 means minimum.'}])
make(27,'Decisions and actions',[
('決める','きめる','kimeru','decide','transitive verb','旅行の日程を決めた。','りょこうのにっていをきめた。','Ryokou no nittei o kimeta.','I decided the travel schedule.','日程を決める','決める takes the chosen thing as を.'),('決まる','きまる','kimaru','be decided','intransitive verb','会議の日程が決まった。','かいぎのにっていがきまった。','Kaigi no nittei ga kimatta.','The meeting schedule was decided.','日程が決まる','決まる describes a decision becoming settled.'),('選択','せんたく','sentaku','choice; selection','noun/suru verb','最適な選択を考えた。','さいてきなせんたくをかんがえた。','Saiteki na sentaku o kangaeta.','I considered the best choice.','選択肢を選ぶ','選択 is a choice among alternatives.'),('判断する','はんだんする','handan suru','judge; decide','suru verb','情報を集めて判断する。','じょうほうをあつめてはんだんする。','Jouhou o atsumete handan suru.','I gather information and make a judgment.','状況を判断する','判断する means reach a judgment based on information.'),('考慮','こうりょ','kouryo','consideration','noun/suru verb','安全を考慮して計画を変更した。','あんぜんをこうりょしてけいかくをへんこうした。','Anzen o kouryo shite keikaku o henkou shita.','I changed the plan with safety in mind.','事情を考慮する','考慮する means take a factor into account.'),('比較する','ひかくする','hikaku suru','compare','suru verb','二つの案を比較して選んだ。','ふたつのあんをひかくしてえらんだ。','Futatsu no an o hikaku shite eranda.','I compared the two proposals and chose one.','価格を比較する','比較する directly compares two or more things.')],[{'type':'meaning','question':'What does 考慮 mean?','options':['consideration','choice','execution'],'answer':'consideration','explanation':'考慮 means consideration.'},{'type':'reading','question':'Reading of 決まる?','options':['きまる','きめる','けつまる'],'answer':'きまる','explanation':'決まる is read きまる.'},{'type':'translation','question':'Translate: 二つの案を比較して選んだ。','answer':'I compared the two proposals and chose one.','explanation':'比較する means compare.'}])
