import json
l=next(x for x in json.load(open('content/vocabulary.json',encoding='utf8'))['lessons'] if x['id']==22)
ctx=[('市役所で手続きを確認した。','しやくしょでてつづきをかくにんした。','Shiyakusho de tetsuzuki o kakunin shita.','I checked the procedure at city hall.'),('駅の掲示を読んで行動した。','えきのけいじをよんでこうどうした。','Eki no keiji o yonde koudou shita.','I read the station notice and acted accordingly.'),('住民に分かりやすく説明された。','じゅうみんにわかりやすくせつめいされた。','Juumin ni wakariyasuku setsumei sareta.','It was explained clearly to the residents.'),('安全のため係員の指示に従った。','あんぜんのためかかりいんのしじにしたがった。','Anzen no tame kakariin no shiji ni shitagatta.','I followed the staff member’s instructions for safety.'),('町内会で新しい案を話し合った。','ちょうないかいであたらしいあんをはなしあった。','Chounaikai de atarashii an o hanashiatta.','We discussed a new proposal at the neighborhood meeting.'),('困ったときは窓口に相談してください。','こまったときはまどぐちにそうだんしてください。','Komatta toki wa madoguchi ni soudan shite kudasai.','If you have trouble, please consult the service counter.')]
rows=[]
for i,x in enumerate(l['items'][:30]):
 w,r,m=x['word'],x['reading'],x['meaning']; ro={'法律':'houritsu','条例':'jourei','権利':'kenri','義務':'gimu','許可':'kyoka','禁止':'kinshi','違反':'ihan','罰':'batsu','犯罪':'hanzai','警察':'keisatsu','裁判':'saiban','裁判所':'saibansho','安全':'anzen','注意':'chuui','非常口':'hijouguchi','避難':'hinan','防災':'bousai','交番':'kouban','騒音':'souon','公共':'koukyou','公園':'kouen','禁煙':'kinen','喫煙':'kitsuen','順番':'junban','列':'retsu','割り込む':'warikomu','守る':'mamoru','破る':'yaburu','届け出':'todokede'} .get(w,w)
 jp,rd,rm,en=ctx[i%6]; jp=jp.replace('手続き',w); rd=rd.replace('てつづき',r); rm=rm.replace('tetsuzuki',ro); en=en.replace('procedure',m)
 rows.append({'word':w,'reading':r,'romaji':ro,'meaning':m,'pos':'noun' if not any(z in w for z in ['込む','守る','破る']) else 'verb','usage':w+'を確認する','example':jp,'example_reading':rd,'example_romaji':rm,'translation':en,'nuance':w+' is used in formal public-life and civic contexts.'})
ex=[{'type':'meaning','question':'What does 条例 mean?','options':['ordinance','crime','queue','park'],'answer':'ordinance','explanation':'条例 means ordinance.'},{'type':'reading','question':'Choose the reading for 非常口.','options':['ひじょうぐち','ひじょぐち','ひじょうこう','ひじょうくち'],'answer':'ひじょうぐち','explanation':'非常口 is read ひじょうぐち.'},{'type':'collocation','question':'Which phrase means “evacuate”?','options':['避難する','列に並ぶ','罰を守る','法律を吸う'],'answer':'避難する','explanation':'避難する means evacuate.'},{'type':'translation','question':'Translate: 安全のため係員の指示に従った。','answer':'I followed the staff member’s instructions for safety.','explanation':'安全 means safety.'},{'type':'particle','question':'Choose: 規則＿＿違反する。','options':['に','を','が','で'],'answer':'に','explanation':'違反する takes に for the rule violated.'},{'type':'contrast','question':'Which word means no smoking?','options':['禁煙','喫煙','騒音','公共'],'answer':'禁煙','explanation':'禁煙 means no smoking.'}]
json.dump({'id':22,'title':'Rules and public life','overview':'Vocabulary for laws, civic rules, safety, public facilities, and responsible behavior.','items':rows,'exercises':ex},open('content/vocab_22.json','w',encoding='utf8'),ensure_ascii=False,indent=2)
