import json
def q(w,r,ro,m,p,e,er,eo,tr,u,n): return {'word':w,'reading':r,'romaji':ro,'meaning':m,'pos':p,'usage':u,'example':e,'example_reading':er,'example_romaji':eo,'translation':tr,'nuance':n}
rows=[
q('身体','しんたい','shintai','body','noun','運動で身体を丈夫にする。','うんどうでしんたいをじょうぶにする。','Undou de shintai o joubu ni suru.','I strengthen my body through exercise.','身体を鍛える','身体 is a formal word for the human body.'),
q('頭','あたま','atama','head','noun','朝から頭が重い。','あさからあたまがおもい。','Asa kara atama ga omoi.','My head has felt heavy since morning.','頭が重い','頭 can mean the physical head or one’s mind/intelligence.'),
q('顔','かお','kao','face','noun','冷たい水で顔を洗った。','つめたいみずでかおをあらった。','Tsumetai mizu de kao o aratta.','I washed my face with cold water.','顔を洗う','顔 is the face or a person’s appearance.'),
q('髪','かみ','kami','hair','noun','美容院で髪を短く切った。','びよういんでかみをみじかくきった。','Biyouin de kami o mijikaku kitta.','I had my hair cut short at the salon.','髪を切る','髪 means the hair on one’s head.'),
q('肩','かた','kata','shoulder','noun','長時間の作業で肩が凝った。','ちょうじかんのさぎょうでかたがこった。','Choujikan no sagyou de kata ga kotta.','My shoulders became stiff after working for a long time.','肩が凝る','肩が凝る is the common expression for stiff shoulders.'),
q('腕','うで','ude','arm','noun','重い箱を両腕で運んだ。','おもいはこをりょううでではこんだ。','Omoi hako o ryouude de hakonda.','I carried the heavy box with both arms.','腕を組む','腕 means arm and can figuratively mean skill.'),
q('手首','てくび','tekubi','wrist','noun','転んで手首を痛めた。','ころんでてくびをいためた。','Koronde tekubi o itameta.','I injured my wrist when I fell.','手首を痛める','手首 is the joint between the hand and forearm.'),
q('指','ゆび','yubi','finger','noun','指で画面を軽く押してください。','ゆびでがめんをかるくおしてください。','Yubi de gamen o karuku oshite kudasai.','Please lightly press the screen with your finger.','指で押す','指 means finger or toe; 足の指 specifies a toe.'),
q('胸','むね','mune','chest','noun','階段を上ると胸が苦しくなる。','かいだんをのぼるとむねがくるしくなる。','Kaidan o noboru to mune ga kurushiku naru.','My chest feels tight when I climb stairs.','胸が苦しい','胸 means chest and can also mean one’s feelings or heart.'),
q('背中','せなか','senaka','back','noun','荷物を背中に背負った。','にもつをせなかにせおった。','Nimotsu o senaka ni seo tta.','I carried the luggage on my back.','背中を伸ばす','背中 is the back of the body.'),
q('腰','こし','koshi','lower back; waist','noun','重い荷物で腰を痛めた。','おもいにもつでこしをいためた。','Omoi nimotsu de koshi o itameta.','I hurt my lower back carrying heavy luggage.','腰を痛める','腰 commonly refers to the lower back, not only the waist.'),
q('脚','あし','ashi','leg','noun','毎日歩いて脚を鍛えている。','まいにちあるいてあしをきたえている。','Mainichi aruite ashi o kitaete iru.','I train my legs by walking every day.','脚を鍛える','脚 usually means the leg, while 足 can mean foot or leg in everyday speech.'),
q('膝','ひざ','hiza','knee','noun','膝に痛みがあるので休んだ。','ひざにいたみがあるのでやすんだ。','Hiza ni itami ga aru node yasunda.','I rested because my knee hurt.','膝が痛む','膝 is the knee joint.'),
q('足首','あしくび','ashikubi','ankle','noun','運動中に足首を捻った。','うんどうちゅうにあしくびをひねった。','Undouchuu ni ashikubi o hinetta.','I twisted my ankle during exercise.','足首を捻る','足首 is the ankle joint.'),
q('肌','はだ','hada','skin','noun','乾燥する季節は肌を保湿する。','かんそうするきせつははだをほしつする。','Kansou suru kisetsu wa hada o hoshitsu suru.','In the dry season, I moisturize my skin.','肌を保湿する','肌 refers to skin, especially its condition or texture.'),
q('歯','は','ha','tooth','noun','食後に歯を磨く習慣がある。','しょくごにはをみがくしゅうかんがある。','Shokugo ni ha o migaku shuukan ga aru.','I have a habit of brushing my teeth after meals.','歯を磨く','歯 is a tooth or teeth; 歯を磨く means brush one’s teeth.'),
q('胃','い','i','stomach','noun','薬を飲んだら胃の痛みが治まった。','くすりをのんだらいのいたみがおさまった。','Kusuri o nondara i no itami ga osamatta.','After taking the medicine, my stomach pain subsided.','胃に負担をかける','胃 is the digestive organ, used in medical and everyday contexts.'),
q('血液','けつえき','ketsueki','blood','noun','健康診断で血液を調べた。','けんこうしんだんでけつえきをしらべた。','Kenkou shindan de ketsueki o shirabeta.','They tested my blood during the checkup.','血液検査','血液 is the formal medical word for blood.'),
q('傷','きず','kizu','wound; scar','noun','傷を消毒して絆創膏を貼った。','きずをしょうどくしてばんそうこうをはった。','Kizu o shoudoku shite bansoukou o hatta.','I disinfected the wound and put on a bandage.','傷を消毒する','傷 can mean a physical wound, damage, or a scar.'),
q('骨','ほね','hone','bone','noun','転倒して腕の骨を折った。','てんとうしてうでのほねをおった。','Tentou shite ude no hone o otta.','I fell and broke a bone in my arm.','骨を折る','骨 means bone; 骨を折る also has a figurative meaning, work hard.'),
q('筋肉','きんにく','kinniku','muscle','noun','運動後に筋肉が痛くなった。','うんどうごにきんにくがいたくなった。','Undougo ni kinniku ga itaku natta.','My muscles became sore after exercising.','筋肉痛','筋肉 refers to muscle tissue; 筋肉痛 is muscle soreness.'),
q('姿勢','しせい','shisei','posture','noun','椅子に座る姿勢を直した。','いすにすわるしせいをなおした。','Isu ni suwaru shisei o naoshita.','I corrected my sitting posture.','姿勢を正す','姿勢 means bodily posture or an attitude toward an issue.'),
q('運動','うんどう','undou','exercise','noun/suru verb','健康のために毎朝運動する。','けんこうのためにまいあさうんどうする。','Kenkou no tame ni maiasa undou suru.','I exercise every morning for my health.','運動不足','運動する means exercise; it can also mean movement or a social movement.'),
q('睡眠','すいみん','suimin','sleep','noun','十分な睡眠を取るようにしている。','じゅうぶんなすいみんをとるようにしている。','Juubun na suimin o toru you ni shite iru.','I try to get enough sleep.','睡眠を取る','睡眠 is formal or health-related vocabulary for sleep.'),
q('休養','きゅうよう','kyuuyou','rest; recuperation','noun/suru verb','疲れたときは無理せず休養する。','つかれたときはむりせずきゅうようする。','Tsukareta toki wa muri sezu kyuuyou suru.','When tired, I rest without overexerting myself.','十分に休養する','休養 emphasizes restorative rest for health.'),
q('食事','しょくじ','shokuji','meal; diet','noun/suru verb','毎日三回、規則正しく食事をする。','まいにちさんかい、きそくただしくしょくじをする。','Mainichi sankai, kisoku tadashiku shokuji o suru.','I eat regular meals three times a day.','食事をする','食事 means a meal or the act of eating.'),
q('手洗い','てあらい','tearai','handwashing','noun/suru verb','外から帰ったら手洗いをする。','そとからかえったらてあらいをする。','Soto kara kaettara tearai o suru.','I wash my hands after coming home.','手洗いを徹底する','手洗い is handwashing, especially as a hygiene measure.'),
q('消毒','しょうどく','shoudoku','disinfection','noun/suru verb','けがをした指を消毒した。','けがをしたゆびをしょうどくした。','Kega o shita yubi o shoudoku shita.','I disinfected the injured finger.','傷口を消毒する','消毒 removes or kills germs on a surface or wound.'),
q('清潔','せいけつ','seiketsu','cleanliness; clean','な-adjective/noun','調理場を清潔に保つ。','ちょうりじょうをせいけつにたもつ。','Chourijou o seiketsu ni tamotsu.','We keep the kitchen clean.','清潔に保つ','清潔 means hygienically clean, not merely tidy.'),
q('化粧','けしょう','keshou','makeup','noun/suru verb','出かける前に化粧をした。','でかけるまえにけしょうをした。','Dekakeru mae ni keshou o shita.','I put on makeup before going out.','化粧をする','化粧 means makeup or applying it.'),
q('髭','ひげ','hige','beard; mustache','noun','毎朝、髭を剃る。','まいあさ、ひげをそる。','Maiasa, hige o soru.','I shave my beard every morning.','髭を剃る','髭 covers facial hair such as a beard or mustache.')]
rows=rows[:30]
ex=[{'type':'meaning','question':'What does 肌 mean?','options':['skin','bone','ankle','posture'],'answer':'skin','explanation':'肌 means skin.'},{'type':'reading','question':'Choose the reading for 血液.','options':['けつえき','けっせき','ちえき','けつい'],'answer':'けつえき','explanation':'血液 is read けつえき.'},{'type':'collocation','question':'Which phrase means “brush one’s teeth”?','options':['歯を磨く','骨を折る','髪を切る','胸が苦しい'],'answer':'歯を磨く','explanation':'歯を磨く is the standard collocation.'},{'type':'translation','question':'Translate: 運動後に筋肉が痛くなった。','answer':'My muscles became sore after exercising.','explanation':'筋肉 means muscle.'},{'type':'particle','question':'Choose: 傷口＿＿消毒する。','options':['を','に','が','で'],'answer':'を','explanation':'The wound is the object of 消毒する.'},{'type':'contrast','question':'Which word means restorative rest?','options':['休養','睡眠','運動','食事'],'answer':'休養','explanation':'休養 emphasizes rest for recovery.'}]
json.dump({'id':18,'title':'Body and care','overview':'Vocabulary for body parts, hygiene, exercise, and health care.','items':rows,'exercises':ex},open('content/vocab_18.json','w',encoding='utf8'),ensure_ascii=False,indent=2)
