import json
from pathlib import Path
A=[]
def add(lesson,pattern,meaning,formation,usage,nuance,mistake,comparison,examples,prompt,options,answer,why,register='neutral; use polite endings in polite conversation'):
    A.append(dict(lesson=lesson,pattern=pattern,meaning=meaning,formation=formation,usage=usage,nuance=nuance,mistake=mistake,comparison=comparison,register=register,examples=[dict(jp=j,reading=r,romaji=m,en=e) for j,r,m,e in examples],question=dict(prompt=prompt,options=options,answer=answer,explanation=why)))
add(1,'つもりだ','intend to; intend not to','V dictionary / Vない + つもりだ','State a plan you currently intend to carry out.','An intention is not a confirmed external arrangement. Vないつもり means intending not to do; Vつもりはない denies an intention.','Do not use Vます before つもり.','ことにする focuses on deciding; つもり describes the resulting intention.',[
('夏休みに日本へ行くつもりです。','なつやすみににほんへいくつもりです。','Natsuyasumi ni Nihon e iku tsumori desu.','I intend to go to Japan during the summer vacation.'),('今日はお酒を飲まないつもりだ。','きょうはおさけをのまないつもりだ。','Kyou wa osake o nomanai tsumori da.','I intend not to drink alcohol today.'),('急いで決めるつもりはありません。','いそいできめるつもりはありません。','Isoide kimeru tsumori wa arimasen.','I have no intention of deciding in a hurry.')],
'来年、留学（する / します / して / し）つもりです。',['する','します','して','し'],'する','つもり takes the dictionary form for an affirmative intention.')
add(5,'ぶりに','for the first time in a period','Duration + ぶりに; Duration + ぶりの + N','Describe doing something again after a gap.','The gap is measured from the last occurrence; it is not a duration spent doing the action.','三年ぶり means after three years, not for three years.','以来 marks continuity since a starting event; ぶり marks a return after absence.',[
('三年ぶりに高校の友達に会った。','さんねんぶりにこうこうのともだちにあった。','Sannen buri ni koukou no tomodachi ni atta.','I met my high-school friend for the first time in three years.'),('久しぶりに母の料理を食べました。','ひさしぶりにははのりょうりをたべました。','Hisashiburi ni haha no ryouri o tabemashita.','I ate my mother’s cooking for the first time in a long while.'),('これは十年ぶりの旅行です。','これはじゅうねんぶりのりょこうです。','Kore wa juunen buri no ryokou desu.','This is my first trip in ten years.')],
'五年（ぶりに / ぶりの / ぶりな / ぶりで）故郷へ帰った。',['ぶりに','ぶりの','ぶりな','ぶりで'],'ぶりに','Use に to modify the action 帰った; の is used before a noun.')
add(5,'おきに','at intervals of; every other unit in some calendar expressions','Time/space interval + おきに','State a regular gap or spacing.','一日おき means every other day. With time expressions such as 一時間おき, usage can mean every hour; use explicit clock times when scheduling must be exact.','Do not confuse 一日おき (one day between events) with 毎日 (daily).','ごとに highlights each unit or occurrence; おきに highlights spacing.',[
('この花には一日おきに水をやります。','このはなにはいちにちおきにみずをやります。','Kono hana ni wa ichinichi oki ni mizu o yarimasu.','I water these flowers every other day.'),('道に十メートルおきに木が植えてある。','みちにじゅうメートルおきにきがうえてある。','Michi ni juu meetoru oki ni ki ga uete aru.','Trees are planted along the road at ten-meter intervals.'),('一行おきに名前を書いてください。','いちぎょうおきになまえをかいてください。','Ichigyou oki ni namae o kaite kudasai.','Please write the names on every other line.')],
'月曜日に水をやり、その後も一日おきにやります。次はいつですか。',['火曜日','水曜日','木曜日','金曜日'],'水曜日','One day is left between Monday and Wednesday.')
add(6,'たて','freshly done','V stem + たて; V stem + たての + N','Describe the fresh state immediately after an action.','Often used with food and recently acquired states: 焼きたて, 入りたて. It cannot freely replace every use of たばかり.','Use 焼きたて, not 焼いたて.','たばかり stresses how recent an event feels; たて emphasizes freshness/newness.',[
('焼きたてのパンを買いました。','やきたてのパンをかいました。','Yakitate no pan o kaimashita.','I bought freshly baked bread.'),('このご飯は炊きたてです。','このごはんはたきたてです。','Kono gohan wa takitate desu.','This rice is freshly cooked.'),('入りたてのころは、何も分かりませんでした。','はいりたてのころは、なにもわかりませんでした。','Hairitate no koro wa, nani mo wakarimasen deshita.','When I had just joined, I did not understand anything.')],
'（焼き / 焼く / 焼いた / 焼いて）たてのパンは温かい。',['焼き','焼く','焼いた','焼いて'],'焼き','Attach たて to the ます stem.')
add(7,'ばよかった','should have; wish I had','Vば + よかった; Vなければ + よかった','Look back with regret at a different choice.','The action in the conditional is typically what did not happen.','The positive ば version often regrets not doing; the negative なければ version regrets doing.','たらどう suggests a future action; ばよかった evaluates a past choice.',[
('傘を持ってくればよかった。','かさをもってくればよかった。','Kasa o motte kureba yokatta.','I wish I had brought an umbrella.'),('あんなことを言わなければよかった。','あんなことをいわなければよかった。','Anna koto o iwanakereba yokatta.','I wish I had not said that.'),('もっと早く予約すればよかったです。','もっとはやくよやくすればよかったです。','Motto hayaku yoyaku sureba yokatta desu.','I should have booked earlier.')],
'遅刻した。もっと早く家を（出れば / 出るなら / 出て / 出ます）よかった。',['出れば','出るなら','出て','出ます'],'出れば','ばよかった expresses regret about not leaving earlier.')
add(10,'ものの','although; despite the fact','V/い-adj plain + ものの; な-adj + なものの; N + であるものの','Acknowledge a fact, then present an unexpected limitation or result.','The first clause is accepted as true. It often sounds more written and restrained than のに.','A noun normally needs である here, not noun + なものの.','のに often carries stronger disappointment; ものの can report contrast calmly.',[
('本を買ったものの、まだ読んでいません。','ほんをかったものの、まだよんでいません。','Hon o katta mono no, mada yonde imasen.','Although I bought the book, I have not read it yet.'),('便利なものの、少し高すぎます。','べんりなものの、すこしたかすぎます。','Benri na mono no, sukoshi takasugimasu.','Although it is convenient, it is a little too expensive.'),('説明は短かったものの、よく分かりました。','せつめいはみじかかったものの、よくわかりました。','Setsumei wa mijikakatta mono no, yoku wakarimashita.','Although the explanation was brief, I understood it well.')],
'便利（な / の / に / だ）ものの、値段が高い。',['な','の','に','だ'],'な','A present affirmative な-adjective takes な before ものの.','mostly written or careful speech')
add(10,'くせに','even though; despite (criticism)','V/い-adj plain + くせに; な-adj + な; N + の','Criticize a mismatch between someone’s position/action and behavior.','Usually directed at another person and can sound accusing or insulting.','Do not use it for neutral polite contrast with a customer; choose のに/けれども.','のに can express surprise or disappointment without the accusing tone of くせに.',[
('知っているくせに、教えてくれない。','しっているくせに、おしえてくれない。','Shitte iru kuse ni, oshiete kurenai.','Even though they know, they will not tell me.'),('暇なくせに、手伝おうとしない。','ひまなくせに、てつだおうとしない。','Hima na kuse ni, tetsudaou to shinai.','They are free, yet they do not even try to help.'),('約束したくせに、また遅れた。','やくそくしたくせに、またおくれた。','Yakusoku shita kuse ni, mata okureta.','Despite having promised, they were late again.')],
'暇（な / の / に / を）くせに、手伝ってくれない。',['な','の','に','を'],'な','暇 is a な-adjective, so な links it to くせに.','casual and critical; use carefully')
add(10,'わりに','considering; for; relatively unexpectedly','V/い-adj plain + わりに; な-adj + な; N + の','Compare the actual quality with the expectation from a known condition.','The surprise can be positive or negative; the standard often has a range, such as price or age.','Use 値段のわりに, not 値段なわりに.','にしては often takes a concrete classification; わりに allows nouns with の and adjectives.',[
('この店は安いわりに、おいしいです。','このみせはやすいわりに、おいしいです。','Kono mise wa yasui wari ni, oishii desu.','This place is good considering how inexpensive it is.'),('値段のわりに、丈夫なかばんです。','ねだんのわりに、じょうぶなかばんです。','Nedan no wari ni, joubu na kaban desu.','It is a sturdy bag for the price.'),('練習したわりに、上手にできなかった。','れんしゅうしたわりに、じょうずにできなかった。','Renshuu shita wari ni, jouzu ni dekinakatta.','Considering how much I practiced, I did not do well.')],
'値段（の / な / に / を）わりに、品質がいい。',['の','な','に','を'],'の','A noun takes の before わりに.')
add(10,'にしては','for; considering (unexpected standard)','V plain / N + にしては','Express that something is unexpected for the stated fact or category.','The first clause supplies the benchmark, often a known fact rather than a hypothetical condition.','Do not insert の after a noun: 初心者にしては.','にとって states a standpoint without implying surprising performance.',[
('初心者にしては、発音がきれいです。','しょしんしゃにしては、はつおんがきれいです。','Shoshinsha ni shite wa, hatsuon ga kirei desu.','For a beginner, their pronunciation is clear.'),('冬にしては、暖かい日ですね。','ふゆにしては、あたたかいひですね。','Fuyu ni shite wa, atatakai hi desu ne.','It is a warm day for winter, isn’t it?' ),('初めて作ったにしては、よくできています。','はじめてつくったにしては、よくできています。','Hajimete tsukutta ni shite wa, yoku dekite imasu.','It is well made for a first attempt.')],
'初心者（にしては / のにしては / なにしては / をしては）、上手です。',['にしては','のにしては','なにしては','をしては'],'にしては','Attach directly to the noun category.')
add(10,'といっても','although I say; even though it is called','Plain clause + といっても; N/な-adj (だ) + といっても','Qualify a statement that might otherwise give an exaggerated impression.','The second clause limits what the first wording suggests.','It does not normally introduce an unrelated contrary fact; the qualification should explain the scope.','ものの contrasts a fact and result; といっても corrects the listener’s likely interpretation.',[
('料理ができるといっても、簡単な物だけです。','りょうりができるといっても、かんたんなものだけです。','Ryouri ga dekiru to itte mo, kantan na mono dake desu.','Although I say I can cook, I can only make simple things.'),('旅行といっても、隣の町へ行くだけです。','りょこうといっても、となりのまちへいくだけです。','Ryokou to itte mo, tonari no machi e iku dake desu.','Although I call it a trip, I am only going to the next town.'),('忙しいといっても、休む時間はあります。','いそがしいといっても、やすむじかんはあります。','Isogashii to itte mo, yasumu jikan wa arimasu.','Although I am busy, I do have time to rest.')],
'忙しい（といっても / にとっても / によっても / としての）、少しは休めます。',['といっても','にとっても','によっても','としての'],'といっても','The second clause limits the impression created by “busy.”')
add(11,'とは限らない','not necessarily; not always','Plain clause + とは限らない; N/な-adj + だとは限らない','Reject a general rule or a conclusion that is not guaranteed.','Some cases can still be true; this is not a complete denial.','Do not translate it as never unless other context supplies that meaning.','はずがない strongly rejects a possibility; とは限らない only denies certainty.',[
('高い物がよいとは限りません。','たかいものがよいとはかぎりません。','Takai mono ga yoi to wa kagirimasen.','Expensive things are not necessarily good.'),('明日も晴れるとは限らない。','あしたもはれるとはかぎらない。','Ashita mo hareru to wa kagiranai.','It will not necessarily be sunny tomorrow too.'),('静かな人が話すのを嫌いだとは限りません。','しずかなひとがはなすのをきらいだとはかぎりません。','Shizuka na hito ga hanasu no o kirai da to wa kagirimasen.','Quiet people do not necessarily dislike talking.')],
'Choose the meaning of 毎回成功するとは限らない。',['Success is not guaranteed every time.','It never succeeds.','It always succeeds.','It must succeed.'],'Success is not guaranteed every time.','The construction denies a universal guarantee, not every successful case.')
add(12,'ないことはない','it is not impossible; not entirely untrue','Vない / い-adj negative + ことはない; N/な-adj + ではないことはない','Offer a qualified positive through a double negative.','Often suggests conditions, difficulty, or reluctance.','Two negatives do not produce a simple negative statement; identify what remains possible.','ことはない after a dictionary verb often reassures “no need to”; the preceding negative changes the logic.',[
('一人でもできないことはない。','ひとりでもできないことはない。','Hitori demo dekinai koto wa nai.','It is not impossible to do it alone.'),('食べられないことはないが、好きではない。','たべられないことはないが、すきではない。','Taberarenai koto wa nai ga, suki dewa nai.','It is not that I cannot eat it, but I do not like it.'),('その気持ちが分からないことはありません。','そのきもちがわからないことはありません。','Sono kimochi ga wakaranai koto wa arimasen.','It is not that I cannot understand that feeling.')],
'できないことはない means:',['It may be possible, with reservations.','It is absolutely impossible.','It is always easy.','It has already been done.'],'It may be possible, with reservations.','The second negative removes the absolute claim that it cannot be done.')
add(12,'しかない','have no choice but to','V dictionary + しかない','Present the only remaining feasible course of action.','Often conveys resignation after alternatives have disappeared.','Do not use the Vない form before しかない for this meaning.','Nしかない means only N exists; Vしかない means no alternative but V.',[
('終電が出たので、歩いて帰るしかない。','しゅうでんがでたので、あるいてかえるしかない。','Shuuden ga deta node, aruite kaeru shika nai.','The last train has left, so I have no choice but to walk home.'),('ここで待つしかありません。','ここでまつしかありません。','Koko de matsu shika arimasen.','There is nothing to do but wait here.'),('間違えた所は、自分で直すしかない。','まちがえたところは、じぶんでなおすしかない。','Machigaeta tokoro wa, jibun de naosu shika nai.','I have no choice but to correct the parts I got wrong myself.')],
'バスがないので、（歩く / 歩いて / 歩き / 歩きます）しかない。',['歩く','歩いて','歩き','歩きます'],'歩く','Use the dictionary form before しかない.')
add(12,'ずに','without doing','Vない minus ない + ずに; する → せずに; 来る → 来ずに（こずに）','Link an unperformed action to the action actually taken.','A more written or compact alternative to ないで.','する is せずに, not しずに.','ないで is common in conversation; ずに is common in written descriptions too.',[
('朝ご飯を食べずに出かけました。','あさごはんをたべずにでかけました。','Asagohan o tabezu ni dekakemashita.','I went out without eating breakfast.'),('誰にも相談せずに決めた。','だれにもそうだんせずにきめた。','Dare ni mo soudan sezu ni kimeta.','I decided without consulting anyone.'),('辞書を見ずに答えてください。','じしょをみずにこたえてください。','Jisho o mizu ni kotaete kudasai.','Please answer without looking at a dictionary.')],
'何も確認（せずに / しずに / するずに / したずに）、送ってしまった。',['せずに','しずに','するずに','したずに'],'せずに','する changes irregularly to せずに.')
add(16,'ことだ（advice）','should; the thing to do is','V dictionary / Vない + ことだ','Give general or practical advice about the best course of action.','Can sound like an instructor stating a principle.','Do not confuse advisory Vことだ with ordinary noun + ことです definitions.','べきだ invokes what is proper; ことだ often offers practical wisdom.',[
('上達したいなら、毎日少し練習することです。','じょうたつしたいなら、まいにちすこしれんしゅうすることです。','Joutatsu shitai nara, mainichi sukoshi renshuu suru koto desu.','If you want to improve, you should practice a little every day.'),('疲れたときは、無理をしないことだ。','つかれたときは、むりをしないことだ。','Tsukareta toki wa, muri o shinai koto da.','When you are tired, the thing to do is not push yourself.'),('まず相手の話を聞くことです。','まずあいてのはなしをきくことです。','Mazu aite no hanashi o kiku koto desu.','First, you should listen to what the other person says.')],
'上手になりたいなら、毎日（練習する / 練習します / 練習して / 練習し）ことだ。',['練習する','練習します','練習して','練習し'],'練習する','The advice construction uses a dictionary or negative plain verb.','advisory; can sound authoritative')
add(17,'てもかまわない','it is all right to; do not mind if','Vて + もかまわない; い-adjくて / N・な-adjで + もかまわない','Grant permission or state that a condition is acceptable.','The speaker says it causes no objection, rather than actively recommends it.','Do not infer obligation: permission means the action is allowed, not required.','てもいい is a more everyday equivalent; てもかまわない may sound slightly more formal.',[
('ここに座ってもかまいませんか。','ここにすわってもかまいませんか。','Koko ni suwatte mo kamaimasen ka.','Would it be all right if I sat here?' ),('少し遅くなってもかまいません。','すこしおそくなってもかまいません。','Sukoshi osoku natte mo kamaimasen.','It is all right if it is a little later.'),('答えは日本語でなくてもかまいません。','こたえはにほんごでなくてもかまいません。','Kotae wa Nihongo de nakute mo kamaimasen.','The answer does not have to be in Japanese.')],
'ここで（待って / 待つ / 待ち / 待ちます）もかまいません。',['待って','待つ','待ち','待ちます'],'待って','The construction attaches to the て-form.')
add(21,'ていただく','humbly receive someone doing a favor','Personに + Vて + いただく','Describe a favor you receive from a respected person.','The grammatical subject is the receiver, often omitted “I/we.”','Do not make the giver the subject with が and keep this same receiving frame.','てくださる makes the respected giver the subject.',[
('先生に作文を見ていただきました。','せんせいにさくぶんをみていただきました。','Sensei ni sakubun o mite itadakimashita.','I had my teacher look over my composition.'),('係の方に場所を教えていただいた。','かかりのかたにばしょをおしえていただいた。','Kakari no kata ni basho o oshiete itadaita.','A staff member kindly told me the location.'),('もう一度説明していただけませんか。','もういちどせつめいしていただけませんか。','Mou ichido setsumei shite itadakemasen ka.','Could you please explain once more?')],
'私は先生（に / が / を / で）説明していただきました。',['に','が','を','で'],'に','に marks the person from whom the speaker receives the favor.','humble/polite; N4-to-N3 keigo bridge')
add(21,'てくださる','a respected person kindly does','Personが/は + Vて + くださる','Honor the person who acts for your benefit.','The favor comes toward the speaker or their in-group.','The polite form is くださいます, not くださります.','ていただく shifts the grammatical subject to the receiver.',[
('先生が丁寧に説明してくださいました。','せんせいがていねいにせつめいしてくださいました。','Sensei ga teinei ni setsumei shite kudasaimashita.','The teacher kindly explained carefully.'),('来てくださって、ありがとうございます。','きてくださって、ありがとうございます。','Kite kudasatte, arigatou gozaimasu.','Thank you for coming.'),('先輩が駅まで案内してくださった。','せんぱいがえきまであんないしてくださった。','Senpai ga eki made annai shite kudasatta.','My senior colleague kindly guided me to the station.')],
'先生が教えて（くださいました / くださりました / いただきました / もらいました）。',['くださいました','くださりました','いただきました','もらいました'],'くださいました','The giver is the subject; くださる has the special polite stem ください.','respectful; N4-to-N3 keigo bridge')
add(20,'させていただく','humbly be allowed to do','Causative Vて + いただく','Present your own action as permitted by another and beneficial to you.','Best used when permission or accommodation is genuinely relevant; overuse for every action sounds cumbersome.','The actor is the speaker’s side, unlike a request that the listener do the original verb.','ていただく receives another person’s action; させていただく receives permission for your action.',[
('先に帰らせていただきます。','さきにかえらせていただきます。','Saki ni kaerasete itadakimasu.','With your permission, I will leave first.'),('この部屋を使わせていただけませんか。','このへやをつかわせていただけませんか。','Kono heya o tsukawasete itadakemasen ka.','Could I please be allowed to use this room?' ),('会議で意見を述べさせていただきました。','かいぎでいけんをのべさせていただきました。','Kaigi de iken o nobesasete itadakimashita.','I was given the opportunity to state my opinion at the meeting.')],
'I request permission to use the room: この部屋を（使わせて / 使って / 使わされて / 使わないで）いただけませんか。',['使わせて','使って','使わされて','使わないで'],'使わせて','Causative + いただく asks permission for the speaker to use it.','humble and formal')
add(21,'お〜になる / ご〜になる','respectful action','お + suitable native V stem + になる; ご + suitable Sino-Japanese action noun + になる','Describe an action of someone you honor.','Many common verbs use special honorific forms instead, such as いらっしゃる and なさる.','Do not use the honorific form for your own action.','お〜する humbles your action toward another; お〜になる raises the other actor.',[
('先生はもうお帰りになりました。','せんせいはもうおかえりになりました。','Sensei wa mou okaeri ni narimashita.','The teacher has already gone home.'),('こちらの資料をご覧になりますか。','こちらのしりょうをごらんになりますか。','Kochira no shiryou o goran ni narimasu ka.','Would you like to look at these materials?' ),('お客様は何をお飲みになりますか。','おきゃくさまはなにをおのみになりますか。','Okyakusama wa nani o onomi ni narimasu ka.','What would you like to drink? (addressing a customer politely)')],
'先生はもう（お帰り / お帰る / お帰って / お帰った）になりました。',['お帰り','お帰る','お帰って','お帰った'],'お帰り','The native verb construction uses the ます stem.','respectful; keigo bridge')
add(21,'お〜する / ご〜する','humbly do for someone','お + suitable native V stem + する; ご + suitable action noun + する','Lower your own or your in-group’s action when it is directed toward someone you respect.','Use established combinations such as お届けする and ご案内する; the prefix is not freely interchangeable.','Do not use this to honor the other person’s action.','お〜になる honors the actor; お〜する humbles the actor’s service toward the recipient.',[
('駅までご案内します。','えきまでごあんないします。','Eki made goannai shimasu.','I will guide you to the station.'),('明日、資料をお届けします。','あした、しりょうをおとどけします。','Ashita, shiryou o otodoke shimasu.','I will deliver the materials tomorrow.'),('詳しいことは後でご説明します。','くわしいことはあとでごせつめいします。','Kuwashii koto wa ato de gosetsumei shimasu.','I will explain the details afterward.')],
'I humbly offer to guide a guest: 私が駅まで（ご案内します / ご案内になります / ご案内なさいます / ご案内くださいます）。',['ご案内します','ご案内になります','ご案内なさいます','ご案内くださいます'],'ご案内します','The speaker performs a service toward the guest and therefore uses the humble construction.','humble; keigo bridge')
add(22,'ば〜ほど','the more ... the more','Vば + same V dictionary + ほど; い-adjければ + same い-adj + ほど; な-adjなら + same な-adjな + ほど','Describe a correlated change along two scales.','Both halves of the first expression repeat the same predicate; the second clause supplies the linked result.','Do not use a ます form after ば: 読めば読むほど.','ほど alone states degree; ば〜ほど explicitly links increasing conditions.',[
('読めば読むほど、面白くなります。','よめばよむほど、おもしろくなります。','Yomeba yomu hodo, omoshiroku narimasu.','The more I read, the more interesting it becomes.'),('駅に近ければ近いほど、家賃が高い。','えきにちかければちかいほど、やちんがたかい。','Eki ni chikakereba chikai hodo, yachin ga takai.','The closer it is to the station, the higher the rent.'),('説明は簡単なら簡単なほどいいです。','せつめいはかんたんならかんたんなほどいいです。','Setsumei wa kantan nara kantan na hodo ii desu.','The simpler the explanation, the better.')],
'読めば（読む / 読み / 読んで / 読みます）ほど、分かるようになります。',['読む','読み','読んで','読みます'],'読む','Repeat the dictionary form after the conditional.')
add(22,'ほど（degree）','to the extent that; enough to','V plain / い-adj plain + ほど; な-adj + なほど; N + ほど','Use a striking comparison or result to show a degree.','The comparison can be figurative, not a literal event that occurred.','Do not translate every ほど as “about”; this use measures intensity.','くらい can similarly show degree; ほど is also common in structured comparisons.',[
('声が出ないほど驚きました。','こえがでないほどおどろきました。','Koe ga denai hodo odorokimashita.','I was so surprised that I could not speak.'),('今日は歩けないほど疲れた。','きょうはあるけないほどつかれた。','Kyou wa arukenai hodo tsukareta.','Today I am so tired I can hardly walk.'),('涙が出るほど笑いました。','なみだがでるほどわらいました。','Namida ga deru hodo waraimashita.','I laughed so much that tears came to my eyes.')],
'涙が（出る / 出ます / 出て / 出）ほど笑った。',['出る','出ます','出て','出'],'出る','A plain verb clause modifies the degree marker ほど.')
add(22,'代わりに','instead of; in exchange for','V plain + 代わりに; N + の代わりに; い-adj + 代わりに; な-adj + な代わりに','Show substitution or a compensating tradeoff.','Identify whether one actor/action replaces another or one advantage balances a disadvantage.','A noun needs の: 先生の代わりに.','一方で simply contrasts aspects; 代わりに often suggests exchange or compensation.',[
('今日は兄の代わりに店を手伝います。','きょうはあにのかわりにみせをてつだいます。','Kyou wa ani no kawari ni mise o tetsudaimasu.','Today I will help at the shop in my older brother’s place.'),('車で行く代わりに、電車で行きました。','くるまでいくかわりに、でんしゃでいきました。','Kuruma de iku kawari ni, densha de ikimashita.','Instead of going by car, I went by train.'),('家賃が安い代わりに、駅から遠いです。','やちんがやすいかわりに、えきからとおいです。','Yachin ga yasui kawari ni, eki kara tooi desu.','The rent is cheap, but in exchange it is far from the station.')],
'兄（の / な / を / に）代わりに出席した。',['の','な','を','に'],'の','Attach a substituting person’s noun with の.')
add(23,'だらけ','covered in; full of undesirable things','N + だらけ; N + だらけの + N','Describe many unwanted items, errors, or marks.','Often carries a negative evaluation; it does not mean a completely filled container in every context.','Do not use it automatically for pleasant abundance; 花がいっぱい is more neutral than 花だらけ.','いっぱい is neutral “full/many”; まみれ strongly suggests something smeared or covered in a substance.',[
('作文が間違いだらけでした。','さくぶんがまちがいだらけでした。','Sakubun ga machigai darake deshita.','My composition was full of mistakes.'),('泥だらけの靴を洗った。','どろだらけのくつをあらった。','Doro darake no kutsu o aratta.','I washed the mud-covered shoes.'),('この部屋はほこりだらけです。','このへやはほこりだらけです。','Kono heya wa hokori darake desu.','This room is covered in dust.')],
'間違いだらけ（の / な / に / を）作文を直す。',['の','な','に','を'],'の','だらけ modifies a following noun through の.')
add(25,'にとって','for; from the standpoint of','N + にとって; N + にとっての + N','State how something is judged by or relevant to a person/group.','Usually followed by evaluation: important, difficult, useful, necessary.','Do not use it merely to name a topic: 日本語について話す, not 日本語にとって話す.','について marks a topic; に対して marks a target or contrast; にとって marks a standpoint.',[
('私にとって、家族が一番大切です。','わたしにとって、かぞくがいちばんたいせつです。','Watashi ni totte, kazoku ga ichiban taisetsu desu.','For me, family is the most important thing.'),('この説明は初心者にとって難しい。','このせつめいはしょしんしゃにとってむずかしい。','Kono setsumei wa shoshinsha ni totte muzukashii.','This explanation is difficult for beginners.'),('これは町にとっての大きな問題です。','これはまちにとってのおおきなもんだいです。','Kore wa machi ni totte no ookina mondai desu.','This is a major problem for the town.')],
'私（にとって / について / によると / をはじめ）、この経験は大切です。',['にとって','について','によると','をはじめ'],'にとって','The sentence gives an evaluation from the speaker’s standpoint.')
add(27,'きる','finish completely; do to the limit','V stem + きる; potential: きれる; negative potential: きれない','Emphasize finishing all of an action or exhausting an amount.','Often the amount or effort is significant.','きれない means cannot finish all, not merely do not do it.','てしまう can stress completion/regret; きる foregrounds total completion.',[
('長い小説を一週間で読みきりました。','ながいしょうせつをいっしゅうかんでよみきりました。','Nagai shousetsu o isshuukan de yomikirimashita.','I finished the entire long novel in one week.'),('量が多くて、食べきれません。','りょうがおおくて、たべきれません。','Ryou ga ookute, tabekiremasen.','There is too much, so I cannot eat it all.'),('最後まで走りきった。','さいごまではしりきった。','Saigo made hashirikitta.','I ran all the way to the finish.')],
'全部は（食べ / 食べる / 食べて / 食べた）きれません。',['食べ','食べる','食べて','食べた'],'食べ','きる and its potential form attach to the verb stem.')
add(27,'かける / かけの','start to; be partway through','V stem + かける; V stem + かけの + N','Describe an action begun but incomplete, or just about to begin.','The precise stage depends on the verb; 読みかけ usually means partially read.','Do not assume the action was completed.','たばかり follows a completed event; かけ highlights an unfinished state.',[
('読みかけの本を机に置いた。','よみかけのほんをつくえにおいた。','Yomikake no hon o tsukue ni oita.','I put the book I had partly read on the desk.'),('何か言いかけて、やめました。','なにかいいかけて、やめました。','Nanika iikakete, yamemashita.','I started to say something, then stopped.'),('食べかけのパンが残っています。','たべかけのパンがのこっています。','Tabekake no pan ga nokotte imasu.','There is some partly eaten bread left.')],
'読みかけ（の / な / に / を）本を持ってきた。',['の','な','に','を'],'の','かけ connects to a following noun with の.')
add(27,'てくる','come to; develop toward now; go do and return','Vて + くる','Track change toward the present/viewpoint, or an action followed by returning.','Distinguish temporal development from literal motion by context.','The direction is toward the viewpoint; future continuation away from now usually uses ていく.','ていく projects change forward; てくる often traces it up to now.',[
('日本語のニュースが少し分かってきました。','にほんごのニュースがすこしわかってきました。','Nihongo no nyuusu ga sukoshi wakatte kimashita.','I have begun to understand Japanese news a little.'),('だんだん寒くなってきた。','だんだんさむくなってきた。','Dandan samuku natte kita.','It has gradually been getting colder.'),('飲み物を買ってきます。','のみものをかってきます。','Nomimono o katte kimasu.','I will go buy drinks and come back.')],
'I will buy a drink and return here: 飲み物を買って（きます / いきます / あります / おります）。',['きます','いきます','あります','おります'],'きます','くる points back toward the current location.','neutral; N4 bridge with N3 discourse applications')
add(27,'ていく','continue on; develop from now; do and go','Vて + いく','Present change continuing forward or movement away from the viewpoint.','Often appears with これから, 今後, 続ける.','Do not use ていく for a change explicitly traced up to now without a forward/away viewpoint.','てくる moves toward now or the speaker; ていく extends onward.',[
('これからも日本語を勉強していきます。','これからもにほんごをべんきょうしていきます。','Kore kara mo Nihongo o benkyou shite ikimasu.','I will continue studying Japanese from now on.'),('町の人口は少しずつ減っていくだろう。','まちのじんこうはすこしずつへっていくだろう。','Machi no jinkou wa sukoshi zutsu hette iku darou.','The town’s population will probably keep decreasing gradually.'),('家を出る前に、朝ご飯を食べていきます。','いえをでるまえに、あさごはんをたべていきます。','Ie o deru mae ni, asagohan o tabete ikimasu.','I will eat breakfast before leaving the house.')],
'これからも練習を（続けて / 続ける / 続けた / 続け）いきます。',['続けて','続ける','続けた','続け'],'続けて','The construction links with the て-form.','neutral; N4 bridge with N3 discourse applications')
add(28,'がる / たがる','show signs of feeling; show a desire to','Selected emotion い-adj stem + がる; な-adj stem + がる; V stem + たがる','Describe observable signs of another person’s feelings or wishes.','Often appears in ている to describe current visible behavior. Only certain emotion words combine naturally.','Do not freely add がる to every adjective; 楽しい → 楽しがる is possible, but factual size adjectives do not use it this way.','たい commonly expresses the speaker’s own desire; たがる reports another person’s displayed desire.',[
('子どもが犬を怖がっています。','こどもがいぬをこわがっています。','Kodomo ga inu o kowagatte imasu.','The child is showing fear of the dog.'),('妹は一人で旅行したがっています。','いもうとはひとりでりょこうしたがっています。','Imouto wa hitori de ryokou shitagatte imasu.','My younger sister wants to travel alone.'),('彼は人前で話すのを嫌がる。','かれはひとまえではなすのをいやがる。','Kare wa hitomae de hanasu no o iyagaru.','He shows reluctance to speak in front of people.')],
'弟は外で遊び（たがって / たいがって / たくがって / たかったがって）います。',['たがって','たいがって','たくがって','たかったがって'],'たがって','The observed-desire form is verb stem + たがる.')
add(28,'ふりをする','pretend to','V/い-adj plain + ふりをする; な-adj + な; N + の','Describe acting as if a state were true while it is not.','The speaker presents a mismatch between reality and performance.','Do not confuse ふり with appearance based on evidence: it implies pretending.','ようだ describes seeming; ふりをする describes intentional performance.',[
('分からないふりをしました。','わからないふりをしました。','Wakaranai furi o shimashita.','I pretended not to understand.'),('弟は寝ているふりをしている。','おとうとはねているふりをしている。','Otouto wa nete iru furi o shite iru.','My younger brother is pretending to be asleep.'),('元気なふりをしなくてもいいですよ。','げんきなふりをしなくてもいいですよ。','Genki na furi o shinakute mo ii desu yo.','You do not have to pretend you are fine.')],
'元気（な / の / に / で）ふりをした。',['な','の','に','で'],'な','元気 is a な-adjective here and needs な before ふり.')
add(28,'てたまらない','extremely; unbearably','Emotion/sensation Vて / い-adjくて / な-adjで + たまらない','Express a feeling or physical sensation that is hard to contain.','Typically describes the speaker’s internal state; third-person descriptions need evidence or reporting.','It is not a general intensifier for every objective fact.','てしょうがない often overlaps; たまらない strongly stresses inability to bear the intensity.',[
('合格して、うれしくてたまらない。','ごうかくして、うれしくてたまらない。','Goukaku shite, ureshikute tamaranai.','I passed, and I am incredibly happy.'),('試験の結果が気になってたまらない。','しけんのけっかがきになってたまらない。','Shiken no kekka ga ki ni natte tamaranai.','I cannot stop thinking about the exam result.'),('今日は眠くてたまりません。','きょうはねむくてたまりません。','Kyou wa nemukute tamarimasen.','I am unbearably sleepy today.')],
'（うれしくて / うれしいで / うれしいな / うれしく）たまりません。',['うれしくて','うれしいで','うれしいな','うれしく'],'うれしくて','An い-adjective uses its くて connective form.')
add(28,'てしょうがない','cannot help feeling; very','Vて / い-adjくて / な-adjで + しょうがない (also しかたがない)','Express an overwhelming or persistent feeling.','Often describes a spontaneous internal reaction rather than an intentional act.','Distinguish standalone しょうがない “it cannot be helped” from this attached intensifier.','てたまらない emphasizes unbearable degree; てしょうがない also conveys inability to control the feeling.',[
('新しい仕事が心配でしょうがない。','あたらしいしごとがしんぱいでしょうがない。','Atarashii shigoto ga shinpai de shouganai.','I cannot help worrying about the new job.'),('次の旅行が楽しみでしかたがない。','つぎのりょこうがたのしみでしかたがない。','Tsugi no ryokou ga tanoshimi de shikata ga nai.','I am looking forward to the next trip so much.'),('のどが渇いてしょうがありません。','のどがかわいてしょうがありません。','Nodo ga kawaite shouga arimasen.','I am terribly thirsty.')],
'心配（で / な / に / の）しょうがない。',['で','な','に','の'],'で','A な-adjective takes で in this construction.')
add(26,'とおりに / どおりに','as; in accordance with','V dictionary/た + とおりに; Nの + とおりに; some N + どおりに','Match instructions, expectations, or a model.','Common noun combinations include 予定どおり and 時間どおり.','Do not pronounce every form どおり: 言ったとおり uses と.','によると gives an information source; とおりに describes acting or occurring in agreement with a model.',[
('説明したとおりに、名前を書いてください。','せつめいしたとおりに、なまえをかいてください。','Setsumei shita toori ni, namae o kaite kudasai.','Please write your name as I explained.'),('予定どおりに出発しました。','よていどおりにしゅっぱつしました。','Yotei doori ni shuppatsu shimashita.','We departed as scheduled.'),('地図のとおりに歩いたのに、道に迷った。','ちずのとおりにあるいたのに、みちにまよった。','Chizu no toori ni aruita noni, michi ni mayotta.','Although I walked as the map showed, I got lost.')],
'先生が言った（とおりに / どおりに / とおりの / どおりの）書いてください。',['とおりに','どおりに','とおりの','どおりの'],'とおりに','After a verb use とおり; に modifies the following action.')
add(30,'ことは〜が','do ... but; it is true ... however','Repeat the same plain predicate around ことは: VことはVが; い-adjことはい-adjが; な-adjなことはな-adjだが','Concede a limited truth before adding a reservation.','The repetition emphasizes that the basic fact is accepted, but it may not meet expectations.','Do not confuse with Vことはない, which often means there is no need.','ものの directly links a fact and contrast; this pattern explicitly concedes the fact through repetition.',[
('読んだことは読んだが、よく覚えていない。','よんだことはよんだが、よくおぼえていない。','Yonda koto wa yonda ga, yoku oboete inai.','I did read it, but I do not remember it well.'),('安いことは安いが、少し古い。','やすいことはやすいが、すこしふるい。','Yasui koto wa yasui ga, sukoshi furui.','It is certainly cheap, but it is a little old.'),('便利なことは便利ですが、毎日は使いません。','べんりなことはべんりですが、まいにちはつかいません。','Benri na koto wa benri desu ga, mainichi wa tsukaimasen.','It is convenient, certainly, but I do not use it every day.')],
'便利（な / の / に / を）ことは便利ですが、高いです。',['な','の','に','を'],'な','The first な-adjective modifies こと and requires な.')
add(13,'そうもない / そうにない','does not look likely to','V stem + そうもない / そうにない','Judge from current evidence that an event is unlikely.','This negates an appearance-based prospect, not a reported fact.','Use 終わりそうにない, not 終わるそうにない.','Vないそうだ is hearsay that something will not happen; V stemそうにない is an evidence-based impression.',[
('今日は雨がやみそうにありません。','きょうはあめがやみそうにありません。','Kyou wa ame ga yamisou ni arimasen.','It does not look as if the rain will stop today.'),('この仕事は五時までに終わりそうもない。','このしごとはごじまでにおわりそうもない。','Kono shigoto wa goji made ni owarisou mo nai.','This job does not look likely to finish by five.'),('彼はまだ帰りそうにない。','かれはまだかえりそうにない。','Kare wa mada kaerisou ni nai.','He does not look ready to go home yet.')],
'仕事は（終わり / 終わる / 終わった / 終わります）そうにない。',['終わり','終わる','終わった','終わります'],'終わり','Appearance そう attaches to the verb stem.')
add(6,'ところに / ところで / ところを','at the moment when; when in a particular situation','V dictionary/ている/た + ところ + appropriate particle','Connect a stage of an action to another event.','ところに often presents an event arriving at that moment; ところで locates the stage; ところを is used with an action affecting the person at that stage.','Choose the particle according to the following predicate, not by English “when” alone.','ところだ states the stage; adding a particle connects that stage to another clause.',[
('出かけようとしていたところに、電話が来た。','でかけようとしていたところに、でんわがきた。','Dekakeyou to shite ita tokoro ni, denwa ga kita.','Just as I was about to go out, a call came.'),('半分読んだところで、休憩しました。','はんぶんよんだところで、きゅうけいしました。','Hanbun yonda tokoro de, kyuukei shimashita.','I took a break when I had read half.'),('困っていたところを、友達に助けてもらった。','こまっていたところを、ともだちにたすけてもらった。','Komatte ita tokoro o, tomodachi ni tasukete moratta.','My friend helped me when I was in trouble.')],
'困っていたところ（を / へ / と / の）、友達に助けてもらいました。',['を','へ','と','の'],'を','The situation of being in trouble is acted upon by the help received.')
add(18,'ようがない','there is no way to','V stem + ようがない; suru noun + のしようがない','State that there is no available method or means.','More specific than generic inability: the means to do it are missing.','This よう is a noun meaning way; it is not ように “so that.”','できない simply says cannot; ようがない explains impossibility through absence of a method.',[
('住所が分からないので、送りようがない。','じゅうしょがわからないので、おくりようがない。','Juusho ga wakaranai node, okuriyou ga nai.','I do not know the address, so there is no way to send it.'),('連絡先がなくて、連絡のしようがありません。','れんらくさきがなくて、れんらくのしようがありません。','Renrakusaki ga nakute, renraku no shiyou ga arimasen.','Without contact details, there is no way to get in touch.'),('説明しようがないほど驚いた。','せつめいしようがないほどおどろいた。','Setsumei shiyou ga nai hodo odoroita.','I was surprised beyond what I can explain.')],
'住所がないので、（送り / 送る / 送って / 送った）ようがない。',['送り','送る','送って','送った'],'送り','Attach the noun よう to the verb stem.')
add(15,'ということだ（report / conclusion）','it is reported that; that means','Plain clause + ということだ; retain だ after N/な-adj for clear quoted statements','Relay information or explain the logical meaning of information.','The source/context tells you whether it is a report or an inference.','Do not translate every instance as hearsay; “つまり” often signals a conclusion.','そうだ伝聞 mainly reports heard information; ということだ can also summarize an implication.',[
('案内によると、明日は休館だということです。','あんないによると、あしたはきゅうかんだということです。','Annai ni yoru to, ashita wa kyuukan da to iu koto desu.','According to the notice, the facility will be closed tomorrow.'),('一人千円なら、三人で三千円ということですね。','ひとりせんえんなら、さんにんでさんぜんえんということですね。','Hitori sen en nara, sannin de sanzen en to iu koto desu ne.','At a thousand yen each, that means three thousand yen for three people, right?' ),('先生から、提出日は金曜日だということを聞きました。','せんせいから、ていしゅつびはきんようびだということをききました。','Sensei kara, teishutsubi wa kinyoubi da to iu koto o kikimashita.','I heard from the teacher that the submission date is Friday.')],
'二人で二千円。つまり、一人千円（ということです / といいますか / にとってです / ようにです）。',['ということです','といいますか','にとってです','ようにです'],'ということです','つまり marks a conclusion drawn from the total cost.')
add(10,'からといって','just because','Plain clause + からといって; often followed by a negative evaluation/conclusion','Reject an inference based only on the stated reason.','A may be true; the speaker denies that A alone justifies B.','Do not treat it as ordinary から for a straightforward reason.','から supports a conclusion; からといって warns that the reason is insufficient.',[
('安いからといって、たくさん買う必要はない。','やすいからといって、たくさんかうひつようはない。','Yasui kara to itte, takusan kau hitsuyou wa nai.','Just because it is cheap, there is no need to buy a lot.'),('日本に住んでいるからといって、日本語が上手だとは限りません。','にほんにすんでいるからといって、にほんごがじょうずだとはかぎりません。','Nihon ni sunde iru kara to itte, Nihongo ga jouzu da to wa kagirimasen.','Living in Japan does not necessarily mean someone is good at Japanese.'),('忙しいからといって、約束を忘れてはいけません。','いそがしいからといって、やくそくをわすれてはいけません。','Isogashii kara to itte, yakusoku o wasurete wa ikemasen.','Being busy is no excuse for forgetting a promise.')],
'Choose the logic of 安いからといって、必要とは限らない。',['Low price does not guarantee need.','It is needed because it is cheap.','It is never cheap.','It is always necessary.'],'Low price does not guarantee need.','The reason is acknowledged but is not enough for the conclusion.')
add(5,'中（ちゅう / じゅう）','during; in progress; throughout; before the period ends','Activity N + 中（ちゅう）; time/place expressions may use 中（じゅう）','Read common compounds as whole expressions rather than applying one universal pronunciation.','勉強中 is during study, 世界中 is throughout the world, 今日中に is by the end of today. Some forms vary in reading/meaning with context.','Do not read every 中 as なか or every time expression as じゅう.','間 focuses on a span/clause; N中 compactly names an ongoing activity or complete scope.',[
('会議中なので、後で電話します。','かいぎちゅうなので、あとででんわします。','Kaigichuu na node, ato de denwa shimasu.','I am in a meeting, so I will call later.'),('今日中に返事をください。','きょうじゅうにへんじをください。','Kyoujuu ni henji o kudasai.','Please reply by the end of today.'),('世界中の人がこの映画を見た。','せかいじゅうのひとがこのえいがをみた。','Sekaijuu no hito ga kono eiga o mita.','People all over the world saw this film.')],
'Read 会議中 and 今日中に.',['かいぎちゅう / きょうじゅうに','かいぎじゅう / きょうなかに','かいぎなか / きょうちゅうに','かいぎちゅう / こんにちなかに'],'かいぎちゅう / きょうじゅうに','These are the standard readings for being in a meeting and by the end of today.')
Path(__file__).with_name('grammar_extra.json').write_text(json.dumps(A,ensure_ascii=False,indent=2),encoding='utf-8')
