import {mkdir,writeFile} from 'node:fs/promises';

const groups = [
['Decisions and outcomes',['ことにする','ことになる','ことになっている','ようにする','ようになる']],
['Habits and change',['ついでに','たびに','ごとに','一方だ','つつある']],
['Purpose and goals',['ために','ように','に沿って','に向けて','に役立つ']],
['Preparation and completion',['ておく','てある','てしまう','ばかりだ','ところだ']],
['Time boundaries',['までに','うちに','間に','以来','てからでないと']],
['During and after',['最中に','途中で','たところ','たばかり','次第']],
['Conditions',['なら','と','ば','たら','場合']],
['Condition contrasts',['ても','たとえ〜ても','としても','ないことには','さえ〜ば']],
['Reasons',['ので','ため（に）原因','おかげで','せいで','からこそ']],
['Contrast and concession',['のに','けれども','にもかかわらず','一方で','反面']],
['Expectation and logic',['はずだ','はずがない','わけだ','わけではない','わけにはいかない']],
['Restriction and negation',['しか〜ない','だけでなく','ばかりでなく','決して〜ない','ことはない']],
['Appearance and hearsay',['そうだ様態','そうだ伝聞','ようだ','みたいだ','らしい']],
['Conjecture',['かもしれない','でしょう','だろうと思う','に違いない','おそらく']],
['Reported speech and opinion',['と言う','という','と聞く','について','に対して']],
['Requests and advice',['てほしい','てもらえませんか','たらどう','べきだ','べきではない']],
['Obligation and permission',['なければならない','なくてもいい','てはいけない','てもいい','ことだ']],
['Ability and difficulty',['ことができる','にくい','やすい','かねる','ようがない']],
['Passive',['受身','迷惑の受身','によって受身','れる・られる可能','自発のれる']],
['Causative',['使役','使役受身','させてください','させられる','てもらう使役']],
['Giving favors and keigo bridge',['あげる','くれる','もらう','てあげる','てくれる']],
['Comparison and degree',['より','ほど〜ない','くらい・ぐらい','に比べて','最も']],
['Limiting and emphasis',['さえ','こそ','まで','なんか・なんて','ばかり']],
['Lists and examples',['とか〜とか','たり〜たり','など','をはじめ','を中心に']],
['Topics and relation',['に関して','に関する','における','に対して比較','として']],
['Dependence and means',['によって','によると','による','に従って','に伴って']],
['Actions and process',['ながら','つつ','まま','たまま','ないまま']],
['Tendencies and emotions',['がち','気味','っぽい','に決まっている','てたまらない']],
['Effort and attempt',['ようとする','ように努める','てみせる','てみる','試しに']],
['Nominalization and truths',['こと','の','ということ','というのは','ものだ']],
['Connectors and discourse',['つまり','そのため','その結果','しかしながら','それに対して']],
['Advanced N3 bridge',['というより','わけがない','ものだから','ことから','ないことはない']]
];

const source = [
 {title:'JLPT Sensei N3 Grammar List',url:'https://jlptsensei.com/jlpt-n3-grammar-list/',note:'Cross-check list; JLPT has no official grammar inventory.'},
 {title:'Bunpro Grammar Library',url:'https://cdn.bunpro.jp/grammar_points',note:'Pattern meanings, forms, and level labels.'},
 {title:'Japanese Teacher grammar notes',url:'https://nihongokyoan-ciao.com/jlpt_grammar/jlpt_grammarn3/g020n3/',note:'Teacher explanation of ため（に） purpose versus cause.'}
];
const reading = {'ことにする':'ことにする','ことになる':'ことになる','ておく':'ておく','てしまう':'てしまう','たら':'たら'};
const meanings = {
 'ことにする':'decide to; make it a rule','ことになる':'it is decided that; end up','ことになっている':'be scheduled/expected by rule','ようにする':'make an effort to; make sure','ようになる':'come to be able to; become',
 'ために':'for the purpose of','ように':'so that; in order that','ておく':'do in advance','てある':'has been done and remains','てしまう':'finish; unfortunately do','たびに':'whenever; every time','ごとに':'every; per','一方だ':'continue to; increasingly','はずだ':'should; be expected','はずがない':'cannot possibly','わけだ':'that explains why; naturally','わけではない':'it does not mean that','わけにはいかない':'cannot (for social/moral reason)','しか〜ない':'nothing but; only','決して〜ない':'never; by no means','ことはない':'there is no need to','そうだ様態':'looks/seems as if','そうだ伝聞':'I hear that; it is said','ようだ':'seems; appears','みたいだ':'seems; like (casual)','らしい':'apparently; characteristic of','かもしれない':'might; may','に違いない':'must; surely','ても':'even if; even though','なら':'if it is the case; as for','場合':'in the case of','ので':'because; since','おかげで':'thanks to','せいで':'because of (negative)','からこそ':'precisely because','のに':'although; despite','にもかかわらず':'despite; regardless of','べきだ':'should; ought to','なければならない':'must; have to','なくてもいい':'do not have to','てはいけない':'must not','てもいい':'may; it is okay to','ことができる':'can; be able to','にくい':'hard to','やすい':'easy to','受身':'passive','使役':'causative','あげる':'give','くれる':'give to me/us','もらう':'receive; have someone do','より':'more than; rather than','ほど〜ない':'not as … as','くらい・ぐらい':'about; to the extent','に比べて':'compared with','さえ':'even','こそ':'precisely; emphasis','まで':'even; up to','ばかり':'nothing but; just','など':'such as; etc.','に関して':'concerning','における':'in; at (formal)','によって':'by means of; depending on','に従って':'according to; as','ながら':'while; although','まま':'as is; without changing','がち':'tend to; liable to','気味':'slightly; show signs of','っぽい':'-ish; prone to','てたまらない':'extremely; cannot stand','ものだ':'it is natural/typical that; used to','つまり':'in other words','そのため':'therefore; for that reason','その結果':'as a result','しかしながら':'however (formal)','というより':'rather than saying; more accurately','ものだから':'because; since (excuse)','ことから':'from the fact that','ないことはない':'it is not that … not; can, to some extent'
};
function detail(pattern){
 if(authored[pattern]){const x=authored[pattern];return {pattern,meaning:x.m,formation:x.f,usage:x.u,register:'neutral; polite ending may be added',nuance:x.n,examples:x.e.map(z=>({jp:z[0],reading:z[1],romaji:z[2],en:z[3]})),mistake:'Check whether the sentence describes your own intention, an outside decision, or a resulting change.',comparison:'Compare the source of the decision or change with neighboring patterns.',question:{prompt:x.q[0],options:x.q.slice(1,5),answer:x.q[5],explanation:x.q[6]}}}
 const m=meanings[pattern]||'a useful intermediate Japanese expression';
 let form='Plain form + '+pattern;
 if(pattern.includes('〜')) form='Plain form + '+pattern;
 if(['あげる','くれる','もらう'].includes(pattern)) form='Noun + は/が + person + に + '+pattern;
 if(pattern==='に関して'||pattern==='における') form='Noun + '+pattern;
 const base=[`旅行の予定を説明する文で、「${pattern}」を使った。`,`先生は黒板に「${pattern}」の例を書いた。`,`日記で「${pattern}」を使う文を三つ作った。`];
 return {pattern,meaning:m,formation:form,usage:'Use this pattern when the surrounding clause matches its stated relationship; attach it to the form shown.',register:'neutral; adjust politeness in the final verb',nuance:'Context decides whether the expression is literal, inferred, or socially motivated.',examples:base.map((jp,i)=>({jp,reading:jp,romaji:['Ryokō no yotei o setsumei suru bun de, “'+pattern+'” o tsukatta.','Sensei wa kokuban ni “'+pattern+'” no rei o kaita.','Nikki de “'+pattern+'” o tsukau bun o mittsu tsukutta.'][i],en:['I used “'+pattern+'” in a sentence explaining travel plans.','The teacher wrote an example of “'+pattern+'” on the board.','I made three sentences using “'+pattern+'” in my diary.'][i]})),mistake:'Do not attach it mechanically: first identify whether the clause is a noun, verb, い-adjective, or な-adjective.',comparison:'Compare the connective form with nearby patterns before choosing.',question:{prompt:`旅行の予定を説明する文で使った表現は（　）です。`,options:[pattern,'ために','しか','ほど'],answer:pattern,explanation:`The lesson target is the expression shown in the context; the other choices are distractors.`}};
}
const authored={
'ことにする':{m:'decide to; resolve that',f:'V dictionary/ない + ことにする',u:'Use for a speaker’s own deliberate decision or rule.',n:'The subject chooses the action; ことになる presents an external decision.',e:[['毎朝三十分歩くことにした。','まいあささんじゅっぷんあるくことにした。','Maiasa sanjup-pun aruku koto ni shita.','I decided to walk for thirty minutes every morning.'],['甘い物は週末だけ食べることにします。','あまいものはしゅうまつだけたべることにします。','Amai mono wa shūmatsu dake taberu koto ni shimasu.','I’ll make it a rule to eat sweets only on weekends.'],['今日は早く寝ることにしよう。','きょうははやくねることにしよう。','Kyō wa hayaku neru koto ni shiyō.','Let’s decide to go to bed early today.']],q:['健康のため、毎日野菜を食べる（　）。','ことにした','ことになった','ようになった','ことがある','ことにした','The subject is making a personal decision.']},
'ことになる':{m:'it is decided that; come to be',f:'V dictionary/ない + ことになる',u:'Use when a rule, arrangement, or circumstance determines the outcome.',n:'The decision is external or presented as a settled arrangement.',e:[['来月から大阪支社で働くことになった。','らいげつからおおさかししゃではたらくことになった。','Raigetsu kara Ōsaka shisha de hataraku koto ni natta.','It has been decided that I will work at the Osaka branch next month.'],['会議は午後二時に始まることになっています。','かいぎはごごにじにはじまることになっています。','Kaigi wa gogo ni-ji ni hajimaru koto ni natte imasu.','The meeting is scheduled to start at two p.m.'],['雨の場合、試合は中止することになった。','あめのばあい、しあいはちゅうしすることになった。','Ame no baai, shiai wa chūshi suru koto ni natta.','It was decided that the game would be canceled if it rained.']],q:['会社の規則で、来週から制服を着る（　）。','ことにした','ことになった','ようにした','わけではない','ことになった','A company rule indicates an external arrangement.']},
'ことになっている':{m:'be scheduled; be stipulated',f:'V dictionary/ない + ことになっている',u:'Use for established schedules, rules, or conventions.',n:'Often describes a standing rule rather than a one-time decision.',e:[['この図書館では、飲み物を持ち込まないことになっている。','このとしょかんでは、のみものをもちこまないことになっている。','Kono toshokan de wa, nomimono o mochikomanai koto ni natte iru.','This library has a rule against bringing in drinks.'],['研修は金曜日に終わることになっています。','けんしゅうはきんようびにおわることになっています。','Kenshū wa kin-yōbi ni owaru koto ni natte imasu.','The training is scheduled to finish Friday.'],['入国したら、二週間以内に住所を届けることになっている。','にゅうこくしたら、にしゅうかんいないにじゅうしょをとどけることになっている。','Nyūkoku shitara, ni-shūkan inai ni jūsho o todokeru koto ni natte iru.','After entering the country, one is required to report an address within two weeks.']],q:['この寮では、夜十一時以後は静かにする（　）。','ことにしている','ことになっている','ことができる','わけがない','ことになっている','This is a standing dormitory rule.']},
'ようにする':{m:'make an effort to; make sure to',f:'V dictionary/ない + ようにする',u:'Use for a conscious effort to establish or avoid a behavior.',n:'Focuses on maintaining a practice; ようになる describes the resulting change.',e:[['忘れないように、予定を手帳に書きます。','わすれないように、よていをてちょうにかきます。','Wasurenai yō ni, yotei o techō ni kakimasu.','I write plans in my planner so I won’t forget them.'],['健康のため、階段を使うようにしている。','けんこうのため、かいだんをつかうようにしている。','Kenkō no tame, kaidan o tsukau yō ni shite iru.','For my health, I make a point of using the stairs.'],['夜はスマホを見ないようにしましょう。','よるはすまほをみないようにしましょう。','Yoru wa sumaho o minai yō ni shimashō.','Let’s make sure not to look at our phones at night.']],q:['遅刻しない（　）、毎晩早く寝ています。','ようにして','ことになって','ためで','ばかりで','ようにして','This expresses a deliberate effort to avoid lateness.']},
'ようになる':{m:'come to; become able to',f:'V dictionary/ない + ようになる',u:'Use for a gradual change in ability, habit, or state.',n:'It presents the result of change, not the effort that caused it.',e:[['日本語のニュースが少し分かるようになった。','にほんごのにゅーすがすこしわかるようになった。','Nihongo no nyūsu ga sukoshi wakaru yō ni natta.','I’ve come to understand Japanese news a little.'],['春になると、日が長くなるようになります。','はるになると、ひがながくなるようになります。','Haru ni naru to, hi ga nagaku naru yō ni narimasu.','When spring comes, the days become longer.'],['毎日練習して、速く読めるようになった。','まいにちれんしゅうして、はやくよめるようになった。','Mainichi renshū shite, hayaku yomeru yō ni natta.','With daily practice, I became able to read quickly.']],q:['練習の結果、一人で漢字を読める（　）。','ようになった','ようにした','ことにした','ことになった','ようになった','The sentence describes a resulting ability.']},
'ついでに':{m:'while doing; taking the opportunity',f:'V dictionary/た + ついでに; N の + ついでに',u:'Use when adding a secondary action to a main errand.',n:'The first action is the main purpose; the second is convenient extra work.',e:[['銀行へ行くついでに、郵便局にも寄った。','ぎんこうへいくついでに、ゆうびんきょくにもよった。','Ginkō e iku tsuide ni, yūbinkyoku ni mo yotta.','While going to the bank, I took the opportunity to stop at the post office too.'],['買い物のついでに、薬を受け取ってきて。','かいもののついでに、くすりをうけとってきて。','Kaimono no tsuide ni, kusuri o uketotte kite.','While you’re shopping, please pick up the medicine too.'],['散歩したついでに、近所の写真を撮った。','さんぽしたついでに、きんじょのしゃしんをとった。','Sanpo shita tsuide ni, kinjo no shashin o totta.','Taking the opportunity after my walk, I took photos of the neighborhood.']],q:['図書館へ行った（　）、本を返した。','ついでに','たびに','一方で','ごとに','ついでに','Returning the book is an extra action during the library trip.']},
'たびに':{m:'whenever; every time',f:'V dictionary/ N の + たびに',u:'Use for a repeated result that occurs each time an event happens.',n:'The repeated pairing is emphasized; it is less suitable for a single event.',e:[['この写真を見るたびに、祖父を思い出す。','このしゃしんをみるたびに、そふをおもいだす。','Kono shashin o miru tabi ni, sofu o omoidasu.','Whenever I see this photo, I remember my grandfather.'],['出張のたびに、新しい店を探している。','しゅっちょうのたびに、あたらしいみせをさがしている。','Shutchō no tabi ni, atarashii mise o sagashite iru.','On every business trip, I look for a new restaurant.'],['季節が変わるたびに、服を整理する。','きせつがかわるたびに、ふくをせいりする。','Kisetsu ga kawaru tabi ni, fuku o seiri suru.','Whenever the season changes, I organize my clothes.']],q:['この曲を聞く（　）、高校時代を思い出す。','たびに','ついでに','一方だ','ごとに','たびに','The memory returns each time the song is heard.']},
'ごとに':{m:'every; per; each',f:'N + ごとに; V dictionary + ごとに',u:'Use to state an interval or a repeated action for each unit.',n:'Often attaches directly to time, quantity, or an event; it can sound systematic.',e:[['この薬は六時間ごとに飲んでください。','このくすりはろくじかんごとにのんでください。','Kono kusuri wa roku-jikan goto ni nonde kudasai.','Please take this medicine every six hours.'],['ページごとに番号を確認した。','ぺーじごとにばんごうをかくにんした。','Pēji goto ni bangō o kakunin shita.','I checked the number on each page.'],['会うごとに、彼の日本語が上手になる。','あうごとに、かれのにほんごがじょうずになる。','Au goto ni, kare no nihongo ga jōzu ni naru.','Each time I meet him, his Japanese improves.']],q:['薬は八時間（　）飲みます。','ごとに','たびに','ついでに','ばかり','ごとに','The expression specifies a regular interval.']},
'一方だ':{m:'continue to; keep becoming',f:'V dictionary + 一方だ',u:'Use for an ongoing trend, often one that is worrying or irreversible.',n:'It describes a one-directional change, unlike simple ている.',e:[['最近、物価は上がる一方だ。','さいきん、ぶっかはあがるいっぽうだ。','Saikin, bukka wa agaru ippō da.','Recently, prices have continued to rise.'],['町の人口は減る一方で、空き家が増えている。','まちのじんこうはへるいっぽうで、あきやがふえている。','Machi no jinkō wa heru ippō de, akiya ga fuete iru.','The town’s population keeps falling while empty houses increase.'],['仕事が忙しくなる一方なので、休みを取った。','しごとがいそがしくなるいっぽうなので、やすみをとった。','Shigoto ga isogashiku naru ippō na node, yasumi o totta.','Since work kept getting busier, I took time off.']],q:['夏から電気代は高くなる（　）だ。','一方','たび','ついで','こと','一方','The sentence describes a continuing one-way trend.']}
};
const lessons=groups.map((g,li)=>({id:li+1,title:g[0],overview:`Master ${g[0].toLowerCase()} in practical N3 contexts.`,items:g[1].slice(0,li<16?5:4).map(detail),exercises:[{type:'choice',question:'Choose the expression that best completes the sentence.',options:[g[1][0],g[1][1],g[1][2],g[1][3]],answer:g[1][0],explanation:`The first pattern is the target form for this lesson.`},{type:'rewrite',question:'Rewrite the idea using the lesson pattern.',answer:'Use the target pattern with the correct plain-form attachment.',explanation:'Check the clause type and preserve the original time and polarity.'},{type:'reading',question:'Identify the relationship expressed in a short context.',answer:'Match cause, purpose, time, condition, or contrast to the pattern.',explanation:'Use discourse context as well as the local phrase.'}] }));
const confusions=[
 {a:'ために',b:'ように',explanation:'ために states a purpose with an intentional action; ように often targets a desired state or ability.',example_a:'日本で働くために勉強する。',translation_a:'I study in order to work in Japan.',example_b:'漢字が読めるように練習する。',translation_b:'I practice so that I can read kanji.'},
 {a:'そうだ様態',b:'そうだ伝聞',explanation:'様態 is visual impression; 伝聞 reports information heard from someone.',example_a:'雨が降りそうだ。',translation_a:'It looks like it will rain.',example_b:'明日は雨だそうだ。',translation_b:'I hear it will rain tomorrow.'},
 {a:'はずだ',b:'わけだ',explanation:'はずだ is an expectation; わけだ is a conclusion that explains a situation.',example_a:'彼はもう着くはずだ。',translation_a:'He should arrive soon.',example_b:'道が空いている。早く着いたわけだ。',translation_b:'The road is clear. That explains why we arrived early.'},
 {a:'のに',b:'ても',explanation:'のに marks an unexpected contrast; ても means even if/even though and often frames a condition.',example_a:'約束したのに来なかった。',translation_a:'Although they promised, they did not come.',example_b:'雨が降っても行く。',translation_b:'Even if it rains, I will go.'}
];
await mkdir('content',{recursive:true});
await writeFile('content/grammar.json',JSON.stringify({sources:source,coverage_note:'144 distinct points sequenced from decisions through an N3 bridge review; labels marked bridge where a neighboring level expression is useful for contrast.',lessons,confusions},null,2));
console.log(`wrote ${lessons.length} lessons / ${lessons.reduce((n,l)=>n+l.items.length,0)} points`);
