import json
from pathlib import Path
out=[]
def add(p,m,f,u,n,err,comp,ex,q,opts,a):
 out.append(dict(pattern=p,meaning=m,formation=f,usage=u,register='neutral; use polite endings where appropriate',nuance=n,mistake=err,comparison=comp,examples=[dict(jp=j,reading=r,romaji=ro,en=en)for j,r,ro,en in ex],question=dict(prompt=q,options=opts,answer=a,explanation=err+' Formation: '+f)))
add('てあげる','do a favor for another person','Vて + あげる','Present an action as benefiting another person.','The actor gives the favor outward, unlike てくれる toward the speaker.','Do not announce てあげます to a superior as a routine polite offer; it can imply doing them a favor.','てもらう presents the recipient as the grammatical subject.',[
('妹に日本語を教えてあげた。','いもうとににほんごをおしえてあげた。','Imouto ni Nihongo o oshiete ageta.','I helped my younger sister by teaching her Japanese.'),('友達の荷物を持ってあげました。','ともだちのにもつをもってあげました。','Tomodachi no nimotsu o motte agemashita.','I carried my friend’s luggage for them.'),('困っている人を手伝ってあげたい。','こまっているひとをてつだってあげたい。','Komatte iru hito o tetsudatte agetai.','I want to help people who are having trouble.')],
'私は妹に漢字を教えて（あげた / くれた / くださった / いらっしゃった）。',['あげた','くれた','くださった','いらっしゃった'],'あげた')
add('より','than; comparison standard','N / plain clause + より','Name the standard that the main description exceeds or differs from.','The thing before より is the comparison baseline.','AよりBのほうが高い says B is more expensive, not A.','ほど〜ない uses a negative predicate to say less ... than.',[
('今日は昨日より暖かいです。','きょうはきのうよりあたたかいです。','Kyou wa kinou yori atatakai desu.','Today is warmer than yesterday.'),('車より電車のほうが速い。','くるまよりでんしゃのほうがはやい。','Kuruma yori densha no hou ga hayai.','The train is faster than the car.'),('聞くより、実際に見るほうが分かりやすい。','きくより、じっさいにみるほうがわかりやすい。','Kiku yori, jissai ni miru hou ga wakariyasui.','It is easier to understand by actually seeing than by hearing about it.')],
'AよりBのほうが高い。Which costs more?',['A','B','Both cost the same.','The sentence gives no comparison.'],'B')
add('ほど〜ない','not as ... as','N / plain clause + ほど + negative predicate','Say that something does not reach the comparison standard.','The noun before ほど supplies the higher standard.','Do not omit the negative ending in the “not as” construction.','AよりB is an affirmative comparison; BはAほど〜ない gives the reverse relation.',[
('この町は東京ほど大きくありません。','このまちはとうきょうほどおおきくありません。','Kono machi wa Toukyou hodo ookiku arimasen.','This town is not as large as Tokyo.'),('今日は昨日ほど寒くない。','きょうはきのうほどさむくない。','Kyou wa kinou hodo samukunai.','Today is not as cold as yesterday.'),('試験は思ったほど難しくなかった。','しけんはおもったほどむずかしくなかった。','Shiken wa omotta hodo muzukashiku nakatta.','The exam was not as difficult as I expected.')],
'Say “not as cold as yesterday”: 昨日ほど（寒くない / 寒い / 寒かった / 寒くなる）。',['寒くない','寒い','寒かった','寒くなる'],'寒くない')
add('くらい・ぐらい','about; to the degree; at least a small amount','Quantity + くらい/ぐらい; plain clause + くらい','Approximate quantities or give a benchmark of degree.','The forms largely overlap; context separates approximate amount from degree or a dismissive minimum.','Do not treat approximate 三人くらい as an exact count.','ほど also marks degree; くらい is especially common for rough amounts.',[
('駅まで十分くらい歩きます。','えきまでじゅっぷんくらいあるきます。','Eki made juppun kurai arukimasu.','I walk about ten minutes to the station.'),('一人では持てないくらい重い。','ひとりではもてないくらいおもい。','Hitori dewa motenai kurai omoi.','It is so heavy that I cannot carry it alone.'),('名前ぐらいは覚えてください。','なまえぐらいはおぼえてください。','Namae gurai wa oboete kudasai.','Please remember at least the name.')],
'三人くらい means:',['about three people','exactly thirty people','fewer than one person','three times every day'],'about three people')
add('に比べて','compared with','N + に比べて; N + と比べて also common','Explicitly introduce a comparison between two things or times.','It states a comparison without necessarily implying surprise.','Use a noun or nominalized clause before に比べて.','にしては judges something against an expected standard and often signals surprise.',[
('去年に比べて、雨が多い。','きょねんにくらべて、あめがおおい。','Kyonen ni kurabete, ame ga ooi.','There is more rain compared with last year.'),('都会に比べて、ここは静かです。','とかいにくらべて、ここはしずかです。','Tokai ni kurabete, koko wa shizuka desu.','Compared with the city, it is quiet here.'),('前の仕事に比べて、通勤時間が短くなった。','まえのしごとにくらべて、つうきんじかんがみじかくなった。','Mae no shigoto ni kurabete, tsuukin jikan ga mijikaku natta.','Compared with my previous job, my commute has become shorter.')],
'去年（に比べて / を比べて / の比べて / な比べて）、暖かい。',['に比べて','を比べて','の比べて','な比べて'],'に比べて')
add('さえ','even; only if (with conditional)','N + さえ; particles may combine: にさえ, でさえ','Pick an extreme example or, with a conditional, a minimum requirement.','The core assertion is surprising even for the marked item.','Do not confuse “even a child” with “only children”; さえ is not だけ.','まで can also mean even, often highlighting an unexpected addition.',[
('自分の名前さえ書けなかった。','じぶんのなまえさえかけなかった。','Jibun no namae sae kakenakatta.','I could not even write my own name.'),('忙しくて、昼ご飯を食べる時間さえない。','いそがしくて、ひるごはんをたべるじかんさえない。','Isogashikute, hirugohan o taberu jikan sae nai.','I am so busy that I do not even have time to eat lunch.'),('この道具は子どもでさえ使えます。','このどうぐはこどもでさえつかえます。','Kono dougu wa kodomo de sae tsukaemasu.','Even children can use this tool.')],
'名前さえ書けない means:',['Cannot even write one’s name.','Can write only names.','Always writes a name.','Must write a name.'],'Cannot even write one’s name.')
add('こそ','precisely; the very thing/person; emphasis','N/phrase + こそ; reason clause + からこそ','Strongly focus the information the speaker considers decisive.','Often contrasts the highlighted item with other possibilities.','It does not normally mean only to the exclusion of everything else.','だけ restricts; こそ emphasizes.',[
('今こそ始めるときです。','いまこそはじめるときです。','Ima koso hajimeru toki desu.','Now is precisely the time to start.'),('こちらこそ、ありがとうございます。','こちらこそ、ありがとうございます。','Kochira koso, arigatou gozaimasu.','It is I who should thank you.'),('失敗したからこそ、分かったことがあります。','しっぱいしたからこそ、わかったことがあります。','Shippai shita kara koso, wakatta koto ga arimasu.','There are things I understood precisely because I failed.')],
'今こそ emphasizes:',['This very moment.','No time at all.','Only yesterday.','Every other day.'],'This very moment.')
add('まで','even; an unexpected further extent','N/phrase + まで','Extend a situation to a surprising additional participant or consequence.','Different from endpoint まで; context can identify either meaning.','Do not automatically translate it as until when it marks an unexpected person or object.','さえ often picks an extreme example; まで highlights how far the situation extends.',[
('先生まで間違えました。','せんせいまでまちがえました。','Sensei made machigaemashita.','Even the teacher made a mistake.'),('財布だけでなく、鍵までなくした。','さいふだけでなく、かぎまでなくした。','Saifu dake de naku, kagi made nakushita.','I lost not only my wallet but even my keys.'),('忙しくて、休日まで働いた。','いそがしくて、きゅうじつまではたらいた。','Isogashikute, kyuujitsu made hataraita.','I was so busy that I worked even on my day off.')],
'先生まで間違えた means:',['Even the teacher made a mistake.','Wait until the teacher.','The teacher never makes mistakes.','Only the teacher may answer.'],'Even the teacher made a mistake.')
add('なんか・なんて','things like; such a thing as; surprised quotation','N + なんか/なんて; plain clause + なんて','Give casual examples, downplay something, or express emotion about a fact.','Tone can be dismissive; context and intonation matter.','Do not use dismissive なんか about something a listener values in formal interaction.','など is a more neutral/formal way to list examples.',[
('お茶なんかどうですか。','おちゃなんかどうですか。','Ocha nanka dou desu ka.','How about something like tea?' ),('一人で全部作ったなんて、すごいです。','ひとりでぜんぶつくったなんて、すごいです。','Hitori de zenbu tsukutta nante, sugoi desu.','It is amazing that you made it all yourself.'),('私なんかには難しすぎます。','わたしなんかにはむずかしすぎます。','Watashi nanka ni wa muzukashisugimasu.','It is too difficult for someone like me.')],
'一人で作ったなんて、すごい expresses:',['Surprise and admiration.','A deadline.','An order to cook.','A confirmed future schedule.'],'Surprise and admiration.')
add('とか〜とか','things such as; or things like','NとかNとか; plain clause + とか','Give casual, non-exhaustive examples.','The list does not necessarily name every possibility.','Keep examples grammatically parallel; do not interpret とか as an exhaustive and-only list.','や is a simple noun list; とか can also follow clauses.',[
('週末は掃除とか洗濯とかをします。','しゅうまつはそうじとかせんたくとかをします。','Shuumatsu wa souji toka sentaku toka o shimasu.','At weekends I do things like cleaning and laundry.'),('パンとか果物とかを買ってきて。','パンとかくだものとかをかってきて。','Pan toka kudamono toka o katte kite.','Please buy things like bread and fruit and bring them back.'),('映画を見るとか、本を読むとかして休みます。','えいがをみるとか、ほんをよむとかしてやすみます。','Eiga o miru toka, hon o yomu toka shite yasumimasu.','I relax by doing things like watching films and reading books.')],
'パンとか果物とか indicates:',['Examples, not necessarily a complete list.','Bread only.','Neither item.','Exactly two mandatory items and nothing else.'],'Examples, not necessarily a complete list.')
add('たり〜たり','do things such as','Vた + り, Vた + り + する; adjectives can also alternate with たり','List representative actions or alternating states.','Although built from the た-form, the final する determines tense.','Do not omit する at the end of an ordinary complete verb-list sentence.','とか can list noun/clause examples; たり uses the た-form and often a final する.',[
('休みの日は本を読んだり、散歩したりします。','やすみのひはほんをよんだり、さんぽしたりします。','Yasumi no hi wa hon o yondari, sanpo shitari shimasu.','On days off I do things like reading and taking walks.'),('昨日は掃除をしたり、料理を作ったりした。','きのうはそうじをしたり、りょうりをつくったりした。','Kinou wa souji o shitari, ryouri o tsukuttari shita.','Yesterday I did things like cleaning and cooking.'),('最近は暑かったり、寒かったりします。','さいきんはあつかったり、さむかったりします。','Saikin wa atsukattari, samukattari shimasu.','Recently it alternates between hot and cold.')],
'本を（読んだり / 読むたり / 読みたり / 読んでたり）、散歩したりします。',['読んだり','読むたり','読みたり','読んでたり'],'読んだり')
add('など','and the like; such as','NやNなど; NなどのN','Mark examples as non-exhaustive.','Common in written explanations and lists.','NなどのN needs の before the following noun.','なんか is more casual and can be dismissive.',[
('野菜や果物などを買いました。','やさいやくだものなどをかいました。','Yasai ya kudamono nado o kaimashita.','I bought things such as vegetables and fruit.'),('住所などの個人情報を確認します。','じゅうしょなどのこじんじょうほうをかくにんします。','Juusho nado no kojin jouhou o kakunin shimasu.','We will check personal information such as your address.'),('会場には学生などが集まっていました。','かいじょうにはがくせいなどがあつまっていました。','Kaijou ni wa gakusei nado ga atsumatte imashita.','Students and others had gathered at the venue.')],
'住所など（の / な / に / を）情報を記入する。',['の','な','に','を'],'の')
add('をはじめ','starting with; including notably','N + をはじめ; N + をはじめとする + N','Name a representative prominent example before referring to the broader group.','The named example is a starting representative, not necessarily first in time.','A following noun normally uses をはじめとする or をはじめとした.','など gives examples without necessarily singling out a prominent representative.',[
('東京をはじめ、多くの都市を訪れました。','とうきょうをはじめ、おおくのとしをおとずれました。','Toukyou o hajime, ooku no toshi o otozuremashita.','I visited many cities, including Tokyo.'),('先生をはじめ、皆さんに感謝しています。','せんせいをはじめ、みなさんにかんしゃしています。','Sensei o hajime, minasan ni kansha shite imasu.','I am grateful to everyone, beginning with my teacher.'),('米をはじめとする食品を輸出しています。','こめをはじめとするしょくひんをゆしゅつしています。','Kome o hajime to suru shokuhin o yushutsu shite imasu.','They export food products, notably rice.')],
'米をはじめ（とする / なする / をする / がする）食品。',['とする','なする','をする','がする'],'とする')
add('に関して','regarding; concerning','N + に関して; N + に関する + N','Introduce the subject of information, inquiry, or discussion.','Generally more formal than について.','Use に関する before a noun, not に関しての as the basic taught attributive form.','について is common conversationally; に関して suits reports and notices.',[
('日程に関して質問があります。','にっていにかんしてしつもんがあります。','Nittei ni kanshite shitsumon ga arimasu.','I have a question regarding the schedule.'),('この制度に関して説明します。','このせいどにかんしてせつめいします。','Kono seido ni kanshite setsumei shimasu.','I will explain this system.'),('環境に関する本を読みました。','かんきょうにかんするほんをよみました。','Kankyou ni kansuru hon o yomimashita.','I read a book about the environment.')],
'環境に（関する / 関して / 関したり / 関します）本を読む。',['関する','関して','関したり','関します'],'関する')
add('に対して比較','whereas; in contrast to','N + に対して; V/い-adj plain + のに対して; N/な-adj + なのに対して','Set two contrasting facts side by side.','Different from the target use in 人に対して丁寧だ; here two clauses or groups contrast.','A verb clause requires の before に対して in this contrasting construction.','一方で similarly contrasts aspects without the same nominalizing attachment.',[
('兄は静かなのに対して、弟はよく話します。','あにはしずかなのにたいして、おとうとはよくはなします。','Ani wa shizuka na no ni taishite, otouto wa yoku hanashimasu.','My older brother is quiet, whereas my younger brother talks a lot.'),('去年は赤字だったのに対して、今年は利益が出た。','きょねんはあかじだったのにたいして、ことしはりえきがでた。','Kyonen wa akaji datta no ni taishite, kotoshi wa rieki ga deta.','Last year there was a deficit, whereas this year there was a profit.'),('平日に対して、休日は利用者が多い。','へいじつにたいして、きゅうじつはりようしゃがおおい。','Heijitsu ni taishite, kyuujitsu wa riyousha ga ooi.','Compared with weekdays, there are many users on holidays.')],
'兄は静か（なの / の / に / を）に対して、弟はにぎやかだ。',['なの','の','に','を'],'なの')
add('によって','depending on; by means of; because of','N + によって; N + による + N','Identify a variable factor, method, or cause; determine the sense from context.','These meanings share a form but are not interchangeable in translation.','Do not interpret every によって as the agent of a passive verb.','によると specifically cites an information source; によって does not by itself mean according to a report.',[
('値段は季節によって変わります。','ねだんはきせつによってかわります。','Nedan wa kisetsu ni yotte kawarimasu.','Prices vary depending on the season.'),('練習によって、発音がよくなった。','れんしゅうによって、はつおんがよくなった。','Renshuu ni yotte, hatsuon ga yoku natta.','My pronunciation improved through practice.'),('大雨による被害が出ました。','おおあめによるひがいがでました。','Ooame ni yoru higai ga demashita.','There was damage caused by heavy rain.')],
'大雨に（よる / よって / よります / よりて）被害。',['よる','よって','よります','よりて'],'よる')
add('によると','according to','Information source N + によると; often followed by そうだ/ということだ','Name where reported information comes from.','It attributes rather than independently verifies the information.','Use a source such as a forecast, report, or person, not a mere cause.','によって can mean due to or depending on; によると is the reporting frame.',[
('天気予報によると、明日は晴れるそうです。','てんきよほうによると、あしたははれるそうです。','Tenki yohou ni yoru to, ashita wa hareru sou desu.','According to the forecast, it will be sunny tomorrow.'),('案内によると、入場は無料です。','あんないによると、にゅうじょうはむりょうです。','Annai ni yoru to, nyuujou wa muryou desu.','According to the notice, admission is free.'),('友達によると、駅前の店は安いらしい。','ともだちによると、えきまえのみせはやすいらしい。','Tomodachi ni yoru to, ekimae no mise wa yasui rashii.','According to my friend, the shop near the station is apparently inexpensive.')],
'天気予報（によると / をはじめ / にとって / に対する）、明日は雨だそうです。',['によると','をはじめ','にとって','に対する'],'によると')
add('に従って','as; in accordance with','N / V dictionary + に従って','Describe parallel change or following a rule/instruction.','With change, the second development accompanies the first.','Vます cannot attach directly; use dictionary form.','とおりに stresses matching a model; に従って can also describe a developing correlation.',[
('説明に従って、番号を押してください。','せつめいにしたがって、ばんごうをおしてください。','Setsumei ni shitagatte, bangou o oshite kudasai.','Please press the number according to the instructions.'),('時間がたつに従って、不安が減りました。','じかんがたつにしたがって、ふあんがへりました。','Jikan ga tatsu ni shitagatte, fuan ga herimashita.','As time passed, my anxiety decreased.'),('町が大きくなるに従って、店も増えた。','まちがおおきくなるにしたがって、みせもふえた。','Machi ga ookiku naru ni shitagatte, mise mo fueta.','As the town grew, the number of shops also increased.')],
'時間が（たつ / たちます / たって / たち）に従って、変わる。',['たつ','たちます','たって','たち'],'たつ')
add('ながら','while doing; although in some established contrasts','V stem + ながら for simultaneous actions','Describe one person doing two actions at the same time.','The action in the main clause is normally the focus.','For this simultaneous-action use, the actor should be the same in both clauses.','間に can locate a separate person’s action inside another event’s duration.',[
('音楽を聞きながら料理をします。','おんがくをききながらりょうりをします。','Ongaku o kikinagara ryouri o shimasu.','I cook while listening to music.'),('地図を見ながら歩きました。','ちずをみながらあるきました。','Chizu o minagara arukimashita.','I walked while looking at the map.'),('メモを取りながら説明を聞いています。','メモをとりながらせつめいをきいています。','Memo o torinagara setsumei o kiite imasu.','I am listening to the explanation while taking notes.')],
'音楽を（聞き / 聞く / 聞いて / 聞いた）ながら、料理をする。',['聞き','聞く','聞いて','聞いた'],'聞き')
add('まま','with a state unchanged','Vた / Vない + まま; Nの / な-adjな / い-adj + まま','Describe preserving a state or doing another action without changing it.','Often points out that a needed change was not made.','Use 靴を履いたまま for keeping shoes on, not 履いてまま.','ながら describes simultaneous actions; まま describes a continuing state.',[
('電気をつけたまま寝てしまいました。','でんきをつけたままねてしまいました。','Denki o tsuketa mama nete shimaimashita.','I fell asleep with the light left on.'),('靴を履いたまま入らないでください。','くつをはいたままはいらないでください。','Kutsu o haita mama hairanaide kudasai.','Please do not enter with your shoes on.'),('何も言わないまま帰った。','なにもいわないままかえった。','Nani mo iwanai mama kaetta.','They went home without saying anything.')],
'窓を（開けた / 開けて / 開けます / 開け）まま出かけた。',['開けた','開けて','開けます','開け'],'開けた')
add('がち','tend to; often fall into','V stem / N + がち; がちなN / がちのN','Describe a recurrent tendency, often undesirable.','More about repeated occurrence than visual resemblance.','Attach to the stem: 忘れがち, not 忘れるがち.','気味 suggests a slight current condition; がち suggests a recurring tendency.',[
('忙しいと、朝ご飯を抜きがちです。','いそがしいと、あさごはんをぬきがちです。','Isogashii to, asagohan o nukigachi desu.','When I am busy, I tend to skip breakfast.'),('最近、授業を休みがちだ。','さいきん、じゅぎょうをやすみがちだ。','Saikin, jugyou o yasumigachi da.','Recently I have tended to miss class.'),('彼は子どものころ病気がちでした。','かれはこどものころびょうきがちでした。','Kare wa kodomo no koro byoukigachi deshita.','He was often ill as a child.')],
'予定を（忘れ / 忘れる / 忘れた / 忘れて）がちです。',['忘れ','忘れる','忘れた','忘れて'],'忘れ')
add('気味','a little; showing a slight tendency','V stem / N + 気味（ぎみ）','Describe a mild condition, often unwanted and felt now or recently.','Common combinations: 疲れ気味, 風邪気味, 遅れ気味.','Do not attach to every adjective freely; learn common combinations.','がち describes repeated tendency; 気味 indicates a slight state.',[
('今日は少し疲れ気味です。','きょうはすこしつかれぎみです。','Kyou wa sukoshi tsukaregimi desu.','I am a little tired today.'),('風邪気味なので、早く寝ます。','かぜぎみなので、はやくねます。','Kazegimi na node, hayaku nemasu.','I feel a bit of a cold coming on, so I will go to bed early.'),('仕事が遅れ気味になっています。','しごとがおくれぎみになっています。','Shigoto ga okuregimi ni natte imasu.','The work is running a little behind schedule.')],
'疲れ気味 is read:',['つかれぎみ','つかれきみ','つかれあじ','つかれけみ'],'つかれぎみ')
add('っぽい','-ish; prone to; having much of a quality','Selected N / V stem / adjective stem + っぽい','Describe a noticeable quality or tendency in an い-adjective-like form.','Common words include 子どもっぽい, 忘れっぽい, 油っぽい.','It conjugates like an い-adjective: 子どもっぽくない.','がち counts recurrence; っぽい presents a characteristic or impression.',[
('この服は少し子どもっぽい。','このふくはすこしこどもっぽい。','Kono fuku wa sukoshi kodomoppoi.','These clothes look a little childish.'),('最近、忘れっぽくなりました。','さいきん、わすれっぽくなりました。','Saikin, wasureppoku narimashita.','I have become forgetful recently.'),('この料理は油っぽくありません。','このりょうりはあぶらっぽくありません。','Kono ryouri wa aburappoku arimasen.','This dish is not greasy.')],
'Choose the negative: 子どもっぽい →',['子どもっぽくない','子どもっぽいではない','子どもっぽくな','子どもっぽなない'],'子どもっぽくない')
add('に決まっている','must be; surely','V/い-adj plain / N / な-adj stem + に決まっている','Express strong subjective certainty.','Can sound dismissive of doubts; the speaker’s certainty is not objective proof.','Do not add だ between a noun and に決まっている.','に違いない is also a strong deduction, often somewhat more measured.',[
('そんな話はうそに決まっている。','そんなはなしはうそにきまっている。','Sonna hanashi wa uso ni kimatte iru.','That story must be a lie.'),('毎日練習したのだから、上手になるに決まっている。','まいにちれんしゅうしたのだから、じょうずになるにきまっている。','Mainichi renshuu shita no dakara, jouzu ni naru ni kimatte iru.','Having practiced every day, of course you will improve.'),('こんな時間なら、店は閉まっているに決まっています。','こんなじかんなら、みせはしまっているにきまっています。','Konna jikan nara, mise wa shimatte iru ni kimatte imasu.','At this hour, the shop is surely closed.')],
'うそ（に / だに / なに / のに）決まっている。',['に','だに','なに','のに'],'に')
add('ようとする','try to; be about to','V volitional + とする','Describe attempting an action or the moment just before it.','The context determines attempt versus imminent action; success is not guaranteed.','This よう is part of the volitional, not dictionary form + よう.','てみる tries an action to see its result; ようとする focuses on attempting to start it.',[
('ドアを開けようとしたが、開かなかった。','ドアをあけようとしたが、あかなかった。','Doa o akeyou to shita ga, akanakatta.','I tried to open the door, but it would not open.'),('寝ようとしたとき、電話が鳴った。','ねようとしたとき、でんわがなった。','Neyou to shita toki, denwa ga natta.','Just as I was about to go to bed, the phone rang.'),('弟は自分で料理を作ろうとしています。','おとうとはじぶんでりょうりをつくろうとしています。','Otouto wa jibun de ryouri o tsukurou to shite imasu.','My younger brother is trying to cook by himself.')],
'ドアを（開けよう / 開けるよう / 開けたよう / 開けてよう）とした。',['開けよう','開けるよう','開けたよう','開けてよう'],'開けよう')
add('てみせる','will definitely do and show; demonstrate by doing','Vて + みせる','Express determination or demonstrate an action for someone to see.','The determined use promises to prove oneself through the result.','It is not identical to simply trying; it can sound confident or challenging.','てみる is exploratory; てみせる demonstrates or resolves to prove.',[
('次の試験には必ず合格してみせる。','つぎのしけんにはかならずごうかくしてみせる。','Tsugi no shiken ni wa kanarazu goukaku shite miseru.','I will definitely pass the next exam and prove it.'),('先生が一度やってみせました。','せんせいがいちどやってみせました。','Sensei ga ichido yatte misemashita.','The teacher demonstrated it once.'),('この仕事を最後まで終わらせてみせます。','このしごとをさいごまでおわらせてみせます。','Kono shigoto o saigo made owarasete misemasu.','I will see this job through to completion.')],
'Determination: 必ず合格（して / する / し / した）みせる。',['して','する','し','した'],'して')
add('てみる','try doing to see the result','Vて + みる','Perform an action as an experiment or experience.','It implies trying the action itself, unlike merely attempting but failing to start.','Use the て-form, not V dictionary + みる.','ようとする focuses on an attempt; てみる explores an outcome.',[
('この料理を食べてみたいです。','このりょうりをたべてみたいです。','Kono ryouri o tabete mitai desu.','I would like to try this dish.'),('分からなければ、先生に聞いてみます。','わからなければ、せんせいにきいてみます。','Wakaranakereba, sensei ni kiite mimasu.','If I do not understand, I will try asking the teacher.'),('別の方法を試してみました。','べつのほうほうをためしてみました。','Betsu no houhou o tameshite mimashita.','I tried out another method.')],
'先生に（聞いて / 聞く / 聞き / 聞いた）みます。',['聞いて','聞く','聞き','聞いた'],'聞いて')
add('こと','nominalize an action or fact','Plain verb/clause + こと; な-adjな / Nの where required','Turn a clause into a noun-like concept.','Common in general rules, abstract facts, and fixed patterns like ことができる.','Do not treat こと and の as interchangeable inside fixed grammatical constructions.','の often suits directly perceived actions; こと often treats an abstract idea.',[
('毎日続けることが大切です。','まいにちつづけることがたいせつです。','Mainichi tsuzukeru koto ga taisetsu desu.','Continuing every day is important.'),('日本語を学ぶことは楽しい。','にほんごをまなぶことはたのしい。','Nihongo o manabu koto wa tanoshii.','Learning Japanese is enjoyable.'),('約束を守ることを忘れないでください。','やくそくをまもることをわすれないでください。','Yakusoku o mamoru koto o wasurenaide kudasai.','Please do not forget to keep your promise.')],
'毎日（続ける / 続けます / 続けて / 続け）ことが大切です。',['続ける','続けます','続けて','続け'],'続ける')
add('の','nominalize a concrete action; refer to one','Plain clause + の; な-adjな / Nな for explanatory nominal clauses','Treat an action as a noun or replace a recoverable noun.','Especially common for observing an action and in のが好き/のは難しい.','Before a perception verb, の is usually natural: 走っているのを見た.','こと commonly treats an abstract idea; の can refer to an observed event or “the one.”',[
('子どもが走っているのを見ました。','こどもがはしっているのをみました。','Kodomo ga hashitte iru no o mimashita.','I saw a child running.'),('早く起きるのは難しいです。','はやくおきるのはむずかしいです。','Hayaku okiru no wa muzukashii desu.','Getting up early is difficult.'),('赤いのをください。','あかいのをください。','Akai no o kudasai.','Please give me the red one.')],
'赤いのをください。の stands for:',['A recoverable item, “the one.”','A reason.','A past action only.','A person’s obligation.'],'A recoverable item, “the one.”')
add('ということ','the fact that; the meaning that','Plain clause + ということ; N/な-adj + だということ','Package the content of a statement as a fact or proposition.','It makes the content being discussed explicit.','Retain the plain copula when quoting a noun predicate: 学生だということ.','こと directly nominalizes; ということ often foregrounds a stated content or conclusion.',[
('明日が休みだということを忘れていました。','あしたがやすみだということをわすれていました。','Ashita ga yasumi da to iu koto o wasurete imashita.','I had forgotten that tomorrow is a day off.'),('彼が来ないということは、まだ聞いていません。','かれがこないということは、まだきいていません。','Kare ga konai to iu koto wa, mada kiite imasen.','I have not yet heard that he is not coming.'),('全員が参加できるということが分かりました。','ぜんいんがさんかできるということがわかりました。','Zenin ga sanka dekiru to iu koto ga wakarimashita.','We found out that everyone can participate.')],
'明日は休み（だ / な / の / に）ということを聞いた。',['だ','な','の','に'],'だ')
add('というのは','as for what is called; defines a term','N/quoted phrase + というのは ... ことだ / 意味だ','Explain a name, term, or concept.','Common when restating unfamiliar vocabulary for the reader.','Do not confuse explanatory というのは with a hearsay report.','ということ packages content; というのは makes that content or term the topic for explanation.',[
('定休日というのは、毎週決まって休む日のことです。','ていきゅうびというのは、まいしゅうきまってやすむひのことです。','Teikyuubi to iu no wa, maishuu kimatte yasumu hi no koto desu.','A regular closing day means the fixed day each week when a business is closed.'),('節約というのは、無駄を減らすことです。','せつやくというのは、むだをへらすことです。','Setsuyaku to iu no wa, muda o herasu koto desu.','Economizing means reducing waste.'),('この印というのは、何を表していますか。','このしるしというのは、なにをあらわしていますか。','Kono shirushi to iu no wa, nani o arawashite imasu ka.','What does this symbol represent?')],
'節約（というのは / にとって / によって / までに）、無駄を減らすことです。',['というのは','にとって','によって','までに'],'というのは')
add('つまり','in other words; that is','Connector at the start of a restatement or conclusion','Restate the previous content more directly or draw its summary implication.','The following clause should clarify the previous point.','Do not use it merely to add an unrelated new fact.','そのため introduces a consequence; つまり reformulates meaning.',[
('今日は定休日です。つまり、店は開いていません。','きょうはていきゅうびです。つまり、みせはあいていません。','Kyou wa teikyuubi desu. Tsumari, mise wa aite imasen.','Today is the regular closing day. In other words, the shop is not open.'),('一人千円です。つまり、二人で二千円になります。','ひとりせんえんです。つまり、ふたりでにせんえんになります。','Hitori sen en desu. Tsumari, futari de nisen en ni narimasu.','It is a thousand yen each. That means two thousand yen for two people.'),('彼は父の兄です。つまり、私のおじです。','かれはちちのあにです。つまり、わたしのおじです。','Kare wa chichi no ani desu. Tsumari, watashi no oji desu.','He is my father’s older brother. In other words, he is my uncle.')],
'父の兄、（つまり / しかし / それでも / ところで）私のおじです。',['つまり','しかし','それでも','ところで'],'つまり')
add('そのため','therefore; for that reason','Previous cause. そのため、result.','Connect an already stated reason to its consequence.','その points back to the preceding situation.','The following content must be a consequence, not simply a rewording.','その結果 emphasizes the outcome of an action/process; そのため can follow any causal situation.',[
('大雪が降りました。そのため、電車が止まりました。','おおゆきがふりました。そのため、でんしゃがとまりました。','Ooyuki ga furimashita. Sono tame, densha ga tomarimashita.','It snowed heavily. As a result, the trains stopped.'),('参加者が増えた。そのため、広い会場を予約した。','さんかしゃがふえた。そのため、ひろいかいじょうをよやくした。','Sankasha ga fueta. Sono tame, hiroi kaijou o yoyaku shita.','The number of participants increased. For that reason, we booked a spacious venue.'),('道が混んでいた。そのため、到着が遅れた。','みちがこんでいた。そのため、とうちゃくがおくれた。','Michi ga konde ita. Sono tame, touchaku ga okureta.','The roads were congested. Consequently, we arrived late.')],
'大雪が降った。（そのため / ところで / それなのに / つまりの）、電車が止まった。',['そのため','ところで','それなのに','つまりの'],'そのため')
add('その結果','as a result','Previous action/process. その結果、outcome.','Identify what happened as the outcome of the preceding effort, process, or event.','Useful for reading the structure of reports.','The result need not be positive; the phrase itself does not mean success.','そのため highlights the causal reason; その結果 foregrounds the outcome.',[
('毎日練習した。その結果、発音がよくなった。','まいにちれんしゅうした。そのけっか、はつおんがよくなった。','Mainichi renshuu shita. Sono kekka, hatsuon ga yoku natta.','I practiced every day. As a result, my pronunciation improved.'),('値段を比べました。その結果、安い店が見つかりました。','ねだんをくらべました。そのけっか、やすいみせがみつかりました。','Nedan o kurabemashita. Sono kekka, yasui mise ga mitsukarimashita.','I compared prices. As a result, I found an inexpensive shop.'),('確認せずに送った。その結果、間違った相手に届いた。','かくにんせずにおくった。そのけっか、まちがったあいてにとどいた。','Kakunin sezu ni okutta. Sono kekka, machigatta aite ni todoita.','I sent it without checking. As a result, it reached the wrong recipient.')],
'その結果 can introduce:',['A positive or negative outcome.','Only a success.','Only a command.','Only a different topic.'],'A positive or negative outcome.')
add('というより','rather than saying; more accurately','Plain clause / N + というより','Replace an initial description with a more accurate one.','The second description is preferred as the better characterization.','Do not treat it as a numerical greater-than comparison.','より compares degree; というより compares ways of describing something.',[
('怒っているというより、心配しています。','おこっているというより、しんぱいしています。','Okotte iru to iu yori, shinpai shite imasu.','Rather than being angry, I am worried.'),('旅行というより、仕事でした。','りょこうというより、しごとでした。','Ryokou to iu yori, shigoto deshita.','It was work rather than a trip.'),('難しいというより、時間がかかる問題です。','むずかしいというより、じかんがかかるもんだいです。','Muzukashii to iu yori, jikan ga kakaru mondai desu.','It is a time-consuming problem rather than a difficult one.')],
'怒っているというより心配している: the better description is',['Worried.','Angry.','Happy.','Indifferent.'],'Worried.')
add('わけがない','there is no way that','V/い-adj plain + わけがない; な-adjな / Nの + わけがない','Strongly reject a possibility based on the speaker’s reasoning.','Often an emphatic judgment rather than mathematical impossibility.','Do not confuse with わけではない, which may only partly deny a claim.','はずがない also expresses strong negative expectation; わけがない is often more emphatic.',[
('一日で全部覚えられるわけがない。','いちにちでぜんぶおぼえられるわけがない。','Ichinichi de zenbu oboerareru wake ga nai.','There is no way I can memorize it all in one day.'),('あの店が無料のわけがありません。','あのみせがむりょうのわけがありません。','Ano mise ga muryou no wake ga arimasen.','There is no way that shop is free.'),('説明を聞いていないのだから、分かるわけがない。','せつめいをきいていないのだから、わかるわけがない。','Setsumei o kiite inai no dakara, wakaru wake ga nai.','Since I have not heard the explanation, there is no way I would understand.')],
'無料（の / に / を / で）わけがない。',['の','に','を','で'],'の')
add('ものだから','because; the reason is (explanation/excuse)','V/い-adj plain + ものだから; な-adjな / Nな + ものだから','Explain a reason, often for an inconvenient result or one’s behavior.','Can sound apologetic or excuse-like; not a neutral technical cause in every setting.','Present noun/な-adjective links commonly use な: 初めてなものだから.','ので gives a comparatively neutral reason; ものだから foregrounds the explanatory justification.',[
('道が混んでいたものだから、遅れました。','みちがこんでいたものだから、おくれました。','Michi ga konde ita mono dakara, okuremashita.','I was late because the roads were congested.'),('初めてなものだから、やり方が分かりませんでした。','はじめてなものだから、やりかたがわかりませんでした。','Hajimete na mono dakara, yarikata ga wakarimasen deshita.','It was my first time, so I did not know how to do it.'),('急いでいたものだから、確認し忘れました。','いそいでいたものだから、かくにんしわすれました。','Isoide ita mono dakara, kakunin shiwasuremashita.','I was in a hurry, so I forgot to check.')],
'初めて（な / の / に / を）ものだから、分からなかった。',['な','の','に','を'],'な')
add('ことから','from the fact that; because (basis)','V/い-adj plain + ことから; な-adjな / Nである + ことから','Use an observable fact as the basis for a conclusion, reason, or name.','Common in explanatory writing, including how places get names.','The first clause should provide the factual basis, not merely a desired purpose.','ために can express purpose; ことから explains reasoning from a fact.',[
('形が星に似ていることから、この名前が付きました。','かたちがほしににていることから、このなまえがつきました。','Katachi ga hoshi ni nite iru koto kara, kono namae ga tsukimashita.','It got this name because its shape resembles a star.'),('駅に近いことから、この場所を選びました。','えきにちかいことから、このばしょをえらびました。','Eki ni chikai koto kara, kono basho o erabimashita.','We chose this location because it is close to the station.'),('電気がついていることから、誰かいると考えた。','でんきがついていることから、だれかいるとかんがえた。','Denki ga tsuite iru koto kara, dareka iru to kangaeta.','From the fact that the light was on, I thought someone was there.')],
'駅に（近い / 近く / 近いな / 近いで）ことから、選んだ。',['近い','近く','近いな','近いで'],'近い')
Path(__file__).with_name('grammar_final_repairs.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
