import json
from pathlib import Path
f=Path('content/grammar.json');d=json.loads(f.read_text(encoding='utf8'))
def put(p,m,form,rows):
 i=next(i for l in d['lessons'] for i in l['items'] if i['pattern']==p)
 i.update(meaning=m,formation=form,usage='Use this expression for the relationship illustrated.',register='neutral',nuance='Read the surrounding clause to identify the intended force.',examples=[{'jp':a,'reading':b,'romaji':c,'en':e} for a,b,c,e in rows],mistake='Check whether the preceding form is a noun, verb, or adjective.',comparison='Compare with the nearest additive or inferential form.',question={'prompt':'Choose the expression that fits.','options':[p,'ために','以来','ばかり'],'answer':p,'explanation':'The context requires this target expression.'})
S={
'だけでなく':('not only; besides','N/ V plain + だけでなく',[('彼は英語だけでなく中国語も話せる。','かれはえいごだけでなくちゅうごくごもはなせる。','Kare wa eigo dake de naku Chūgokugo mo hanaseru.','He can speak not only English but also Chinese.'),('この店は安いだけでなく親切だ。','このみせはやすいだけでなくしんせつだ。','Kono mise wa yasui dake de naku shinsetsu da.','This shop is not only cheap but also friendly.'),('雨だけでなく風も強かった。','あめだけでなくかぜもつよかった。','Ame dake de naku kaze mo tsuyokatta.','Not only rain but also strong wind occurred.')]),
'ばかりでなく':('not only; as well as (formal)','N/ V plain + ばかりでなく',[('彼は歌ばかりでなく絵も上手だ。','かれはうたばかりでなくえもじょうずだ。','Kare wa uta bakari de naku e mo jōzu da.','He is good not only at singing but also painting.'),('国内ばかりでなく海外でも販売する。','こくないばかりでなくかいがいでもはんばいする。','Kokunai bakari de naku kaigai demo hanbai suru.','We sell it both domestically and overseas.'),('知識ばかりでなく経験も必要だ。','ちしきばかりでなくけいけんもひつようだ。','Chishiki bakari de naku keiken mo hitsuyō da.','Not only knowledge but also experience is needed.')]),
'に違いない':('must; surely','Plain form + に違いない',[('彼はもう帰ったに違いない。','かれはもうかえったにちがいない。','Kare wa mō kaetta ni chigai nai.','He must have gone home already.'),('これは本物に違いありません。','これはほんものにちがいありません。','Kore wa honmono ni chigai arimasen.','This must be genuine.'),('努力したから成功したに違いない。','どりょくしたからせいこうしたにちがいない。','Doryoku shita kara seikō shita ni chigai nai.','He must have succeeded because he worked hard.')]),
'おそらく':('probably; most likely','おそらく + clause',[('おそらく明日は晴れる。','おそらくあしたははれる。','Osoraku ashita wa hareru.','It will probably be sunny tomorrow.'),('おそらく彼は知らないだろう。','おそらくかれはしらないだろう。','Osoraku kare wa shiranai darō.','He probably does not know.'),('おそらく予定どおりに進む。','おそらくよていどおりにすすむ。','Osoraku yotei dōri ni susumu.','It will most likely proceed as planned.')]),
'と言う':('say; call; be called','clause + と言う',[('母は「気をつけて」と言った。','はははきをつけてといった。','Haha wa ki o tsukete to itta.','My mother said, “Be careful.”'),('彼は来週行くと言っていた。','かれはらいしゅういくといっていた。','Kare wa raishū iku to itte ita.','He said he would go next week.'),('これは日本語で何と言いますか。','これはにほんごでなんといいますか。','Kore wa nihongo de nan to iimasu ka.','What do you call this in Japanese?')]),
'という':('called; the fact that; quotation marker','N + という + N',[('田中という人から電話があった。','たなかというひとからでんわがあった。','Tanaka to iu hito kara denwa ga atta.','A person called Tanaka phoned.'),('合格したという知らせを受けた。','ごうかくしたというしらせをうけた。','Gōkaku shita to iu shirase o uketa.','I received news that I passed.'),('「ありがとう」という言葉を覚えた。','ありがとうということばをおぼえた。','Arigatō to iu kotoba o oboeta.','I learned the word “thank you.”')]),
'と聞く':('hear that; ask','plain clause + と聞く',[('明日は休みだと聞いた。','あしたはやすみだときいた。','Ashita wa yasumi da to kiita.','I heard tomorrow is a holiday.'),('先生に試験の日を聞いた。','せんせいにしけんのひをきいた。','Sensei ni shiken no hi o kiita.','I asked the teacher the exam date.'),('この店は有名だと聞いている。','このみせはゆうめいだときいている。','Kono mise wa yūmei da to kiite iru.','I hear this shop is famous.')]),
'について':('about; concerning','N + について',[('日本の歴史について調べている。','にほんのれきしについてしらべている。','Nihon no rekishi ni tsuite shirabete iru.','I am researching Japanese history.'),('先生に進路について相談した。','せんせいにしんろについてそうだんした。','Sensei ni shinro ni tsuite sōdan shita.','I consulted my teacher about my career path.'),('この問題について意見を述べます。','このもんだいについていけんをのべます。','Kono mondai ni tsuite iken o nobemasu.','I will state my opinion on this issue.')]),
'に対して':('toward; in contrast to','N + に対して',[('質問に対して丁寧に答えた。','しつもんにたいしてていねいにこたえた。','Shitsumon ni taishite teinei ni kotaeta.','I answered the question politely.'),('兄が静かなのに対して弟は活発だ。','あにがしずかなのにたいしておとうとはかっぱつだ。','Ani ga shizuka na no ni taishite otōto wa kappatsu da.','In contrast to the quiet older brother, the younger brother is lively.'),('環境問題に対して関心が高い。','かんきょうもんだいにたいしてかんしんがたかい。','Kankyō mondai ni taishite kanshin ga takai.','There is strong interest toward environmental issues.')]),
'てほしい':('want someone to; hope that','Vて + ほしい',[('もっとゆっくり話してほしい。','もっとゆっくりはなしてほしい。','Motto yukkuri hanashite hoshii.','I want you to speak more slowly.'),('明日までに返事をしてほしい。','あしたまでにへんじをしてほしい。','Ashita made ni henji o shite hoshii.','I want you to reply by tomorrow.'),('無理をしないでほしい。','むりをしないでほしい。','Muri o shinaide hoshii.','I want you not to overdo it.')]),
'てもらえませんか':('could you; would you','Vて + もらえませんか',[('窓を閉めてもらえませんか。','まどをしめてもらえませんか。','Mado o shimete moraemasen ka.','Could you close the window?'),('もう一度説明してもらえませんか。','もういちどせつめいしてもらえませんか。','Mō ichido setsumei shite moraemasen ka.','Could you explain it once more?'),('住所を書いてもらえませんか。','じゅうしょをかいてもらえませんか。','Jūsho o kaite moraemasen ka.','Could you write your address?')]),
'たらどう':('why don’t you; how about','Vたらどう',[('病院へ行ったらどうですか。','びょういんへいったらどうですか。','Byōin e ittara dō desu ka.','Why don’t you go to a hospital?'),('先生に聞いたらどう。','せんせいにきいたらどう。','Sensei ni kiitara dō.','How about asking the teacher?'),('少し休んだらどうですか。','すこしやすんだらどうですか。','Sukoshi yasundara dō desu ka.','Why don’t you rest a little?')])}
for p,(m,form,rows) in S.items(): put(p,m,form,rows)
f.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8');print('patched',len(S))
