import json
from pathlib import Path
path=Path('content/grammar.json'); d=json.loads(path.read_text(encoding='utf8'))
def put(pat,m,f,ex,q,opts,ans,nu='Context determines the exact force.'):
 x=next(i for l in d['lessons'] for i in l['items'] if i['pattern']==pat)
 x.update(meaning=m,formation=f,usage='Use this form for the relationship shown in the examples.',register='neutral',nuance=nu,examples=[{'jp':a,'reading':b,'romaji':c,'en':e} for a,b,c,e in ex],mistake='Check the preceding clause form and polarity.',comparison='Distinguish this form by its condition, cause, or contrast.',question={'prompt':q,'options':opts,'answer':ans,'explanation':'The sentence context requires the target relationship.'})
sets={
'たとえ〜ても':('even if; even though','たとえ + Vて/adjくて + も',[('たとえ忙しくても、約束は守る。','たとえいそがしくても、やくそくはまもる。','Tatoe isogashikute mo yakusoku wa mamoru.','Even if I am busy, I will keep my promise.'),('たとえ反対されても、挑戦したい。','たとえはんたいされても、ちょうせんしたい。','Tatoe hantai sarete mo chōsen shitai.','Even if people oppose me, I want to try.'),('たとえ失敗しても、経験になる。','たとえしっぱいしても、けいけんになる。','Tatoe shippai shite mo keiken ni naru.','Even if I fail, it will be experience.')],'（　）反対されても、挑戦したい。',['たとえ','もし','せっかく','まるで'],'たとえ'),
'としても':('even assuming; even if','V/adj plain + としても',[('今から出ても、間に合わないとしても行く。','いまからでても、まにあわないとしてもいく。','Ima kara dete mo maniawanai to shite mo iku.','Even assuming we will not make it, I will go.'),('冗談だとしても、言い過ぎだ。','じょうだんだとしても、いいすぎだ。','Jōdan da to shite mo iisugi da.','Even if it was a joke, that was too much.'),('高いとしても、必要なら買う。','たかいとしても、ひつようならかう。','Takai to shite mo hitsuyō nara kau.','Even if it is expensive, I will buy it if necessary.')],'冗談だ（　）、その言い方はよくない。',['としても','たとえば','おかげで','ばかり'],'としても'),
'ないことには':('unless; without doing','Vない + ことには',[('実際に見ないことには、判断できない。','じっさいにみないことには、はんだんできない。','Jissai ni minai koto ni wa handan dekinai.','Unless I see it myself, I cannot judge.'),('努力しないことには、結果は出ない。','どりょくしないことには、けっかはでない。','Doryoku shinai koto ni wa kekka wa denai.','Without effort, there will be no result.'),('本人に聞かないことには分からない。','ほんにんにきかないことにはわからない。','Honnin ni kikanai koto ni wa wakaranai.','Unless we ask the person, we cannot know.')],'本人に聞か（　）分からない。',['ないことには','たとえ','おかげで','ほど'],'ないことには'),
'さえ〜ば':('if only; as long as','Nさえ + Vば',[('時間さえあれば、手伝えます。','じかんさえあれば、てつだえます。','Jikan sae areba tetsudaemasu.','As long as I have time, I can help.'),('薬を飲みさえすれば、よくなる。','くすりをのみさえすれば、よくなる。','Kusuri o nomi sae sureba yoku naru.','If you just take the medicine, you will get better.'),('住所さえ分かれば、連絡できる。','じゅうしょさえわかれば、れんらくできる。','Jūsho sae wakareba renraku dekiru.','As long as I know the address, I can contact them.')],'住所（　）分かれば、連絡できます。',['さえ','こそ','まで','しか'],'さえ'),
'ので':('because; since','V/adj plain + ので; N/な-adj な + ので',[('雨なので、試合は中止です。','あめなので、しあいはちゅうしです。','Ame na node shiai wa chūshi desu.','Since it is raining, the game is canceled.'),('体調が悪いので、早く帰ります。','たいちょうがわるいので、はやくかえります。','Taichō ga warui node hayaku kaerimasu.','Because I feel ill, I will go home early.'),('静かなので、ここで勉強できる。','しずかなので、ここでべんきょうできる。','Shizuka na node koko de benkyō dekiru.','Because it is quiet, I can study here.')],'体調が悪い（　）、早く帰ります。',['ので','のに','せいで','こそ'],'ので'),
'ため（に）原因':('due to; because of','Nの/V plain + ため（に）',[('大雨のため、電車が遅れています。','おおあめのため、でんしゃがおくれています。','Ōame no tame densha ga okurete imasu.','Due to heavy rain, trains are delayed.'),('故障したために、機械が止まった。','こしょうしたために、きかいがとまった。','Koshō shita tame ni kikai ga tomatta.','Because it broke, the machine stopped.'),('事故のため、道路が通行止めになった。','じこのため、どうろがつうこうどめになった。','Jiko no tame dōro ga tsūkōdome ni natta.','Due to an accident, the road was closed.')],'大雨の（　）、電車が遅れている。',['ため','おかげで','こそ','のに'],'ため')}
for p,(m,f,ex,q,op,a) in sets.items(): put(p,m,f,ex,q,op,a)
path.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8'); print('patched',len(sets))
