import json
from pathlib import Path
path=Path('content/grammar.json');d=json.loads(path.read_text(encoding='utf8'))
def put(p,m,f,ex,q,a):
 i=next(i for l in d['lessons'] for i in l['items'] if i['pattern']==p); i.update(meaning=m,formation=f,usage='Use this construction in the relationship shown by the examples.',register='neutral',nuance='Tense and polarity determine the exact reading.',examples=[{'jp':x[0],'reading':x[1],'romaji':x[2],'en':x[3]} for x in ex],mistake='Use the required connective form.',comparison='Check the clause relationship before selecting a similar form.',question={'prompt':q,'options':[a,'ために','以来','ばかり'],'answer':a,'explanation':'The context requires this construction.'})
S={
'なら':('if it is the case; as for','N/な-adj + なら; V/い-adj plain + なら',[('東京へ行くなら、浅草も見てください。','とうきょうへいくなら、あさくさもみてください。','Tōkyō e iku nara, Asakusa mo mite kudasai.','If you are going to Tokyo, please see Asakusa too.'),('必要なら、コピーを送ります。','ひつようなら、こぴーをおくります。','Hitsuyō nara, kopī o okurimasu.','If necessary, I will send a copy.'),('電車なら、十分で着きます。','でんしゃなら、じゅっぷんでつきます。','Densha nara, juppun de tsukimasu.','If you take the train, you will arrive in ten minutes.')],'東京へ行く（　）、この店がおすすめです。','なら'),
'と':('when; whenever; if','V dictionary + と',[('春になると桜が咲く。','はるになるとさくらがさく。','Haru ni naru to sakura ga saku.','When spring comes, the cherry blossoms bloom.'),('このボタンを押すと画面が変わる。','このぼたんをおすとがめんがかわる。','Kono botan o osu to gamen ga kawaru.','When you press this button, the screen changes.'),('急がないと電車に遅れる。','いそがないとでんしゃにおくれる。','Isoganai to densha ni okureru.','If you do not hurry, you will miss the train.')],'春になる（　）暖かくなる。','と'),
'ば':('if; when','Vば/い-adjければ + ば',[('安ければ買います。','やすければかいます。','Yasukereba kaimasu.','If it is cheap, I will buy it.'),('駅に着けば電話してください。','えきにつけばでんわしてください。','Eki ni tsukeba denwa shite kudasai.','Please call when you arrive at the station.'),('練習すれば上手になる。','れんしゅうすればじょうずになる。','Renshū sureba jōzu ni naru.','If you practice, you will improve.')],'練習すれ（　）上手になる。','ば'),
'たら':('if; when; after','Vたら/い-adjかったら + たら',[('雨が降ったら試合を中止します。','あめがふったらしあいをちゅうしします。','Ame ga futtara shiai o chūshi shimasu.','If it rains, we will cancel the game.'),('仕事が終わったら連絡する。','しごとがおわったられんらくする。','Shigoto ga owattara renraku suru.','I will contact you after work ends.'),('暇だったら手伝ってください。','ひまだったらてつだってください。','Hima dattara tetsudatte kudasai.','If you are free, please help.')],'仕事が終わっ（　）電話します。','たら'),
'場合':('in the case of','Nの/V plain + 場合（は）',[('火事の場合は階段を使ってください。','かじのばあいはかいだんをつかってください。','Kaji no baai wa kaidan o tsukatte kudasai.','In case of fire, use the stairs.'),('遅れる場合は連絡してください。','おくれるばあいはれんらくしてください。','Okureru baai wa renraku shite kudasai.','If you will be late, please contact us.'),('雨の場合、屋内で行います。','あめのばあい、おくないでおこないます。','Ame no baai, okunai de okonaimasu.','In case of rain, we will hold it indoors.')],'雨の（　）、屋内で行います。','場合'),
'ても':('even if; even though','Vて/い-adjくて + も',[('雨が降っても出かけます。','あめがふってもでかけます。','Ame ga futte mo dekakemasu.','Even if it rains, I will go out.'),('高くても必要なら買う。','たかくてもひつようならかう。','Takakute mo hitsuyō nara kau.','Even if it is expensive, I will buy it if necessary.'),('何度読んでも分からない。','なんどよんでもわからない。','Nando yonde mo wakaranai.','No matter how many times I read it, I do not understand.')],'雨が降っ（　）行きます。','ても')}
for p,(m,f,ex,q,a) in S.items():put(p,m,f,ex,q,a)
path.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8');print('patched',len(S))
