import json
from pathlib import Path
p=Path('content/grammar.json'); d=json.loads(p.read_text(encoding='utf8'))
def put(pat,m,f,ex,q,op,a):
    x=next(i for l in d['lessons'] for i in l['items'] if i['pattern']==pat)
    x.update(meaning=m,formation=f,usage='Use this form when the context calls for the relationship illustrated.',register='neutral',nuance='Interpret the pattern with the tense and polarity of its clause.',examples=[dict(jp=j,reading=r,romaji=ro,en=e) for j,r,ro,e in ex],mistake='Verify the attachment before conjugating.',comparison='Compare the timing or condition with nearby forms.',question=dict(prompt=q,options=op,answer=a,explanation='The context and attachment select the answer.'))
V={
'てからでないと':('unless; not until','Vて + からでないと', [('予約してからでないと入れません。','よやくしてからでないとはいれません。','Yoyaku shite kara denai to hairemasen.','You cannot enter unless you reserve.'),('説明を読んでからでないと使えない。','せつめいをよんでからでないとつかえない。','Setsumei o yonde kara denai to tsukaenai.','It cannot be used until you read the instructions.'),('許可を取ってからでないと撮影できません。','きょかをとってからでないとさつえいできません。','Kyoka o totte kara denai to satsuei dekimasen.','You cannot film unless you get permission.')], '説明を読んで（　）使えない。',['からでないと','ついでに','ばかりで','以来'],'からでないと'),
'最中に':('in the middle of','Nの/Vている + 最中に',[('食事の最中に電話が鳴った。','しょくじのさいちゅうにでんわがなった。','Shokuji no saichū ni denwa ga natta.','The phone rang in the middle of dinner.'),('会議をしている最中に停電した。','かいぎをしているさいちゅうにていでんした。','Kaigi o shite iru saichū ni teiden shita.','The power went out during the meeting.'),('試験の最中に外で大きな音がした。','しけんのさいちゅうにそとでおおきなおとがした。','Shiken no saichū ni soto de ōkina oto ga shita.','A loud noise occurred outside during the exam.')],'会議の（　）停電した。',['最中に','次第','以来','ために'],'最中に'),
'途中で':('on the way; midway through','Nの/Vている + 途中で',[('学校へ行く途中で友達に会った。','がっこうへいくとちゅうでともだちにあった。','Gakkō e iku tochū de tomodachi ni atta.','I met a friend on the way to school.'),('映画の途中で寝てしまった。','えいがのとちゅうでねてしまった。','Eiga no tochū de nete shimatta.','I fell asleep midway through the movie.'),('帰宅する途中で雨が降り始めた。','きたくするとちゅうであめがふりはじめた。','Kitaku suru tochū de ame ga furihajimeta.','It started raining on my way home.')],'映画の（　）寝てしまった。',['途中で','最中に','次第','以来'],'途中で'),
'たところ':('when; just after doing','Vた + ところ',[('店員に聞いたところ、在庫があった。','てんいんにきいたところ、ざいこがあった。','Ten-in ni kiita tokoro, zaiko ga atta.','When I asked the clerk, there was stock.'),('窓を開けたところ、涼しい風が入った。','まどをあけたところ、すずしいかぜがはいった。','Mado o aketa tokoro, suzushii kaze ga haitta.','When I opened the window, a cool breeze came in.'),('調べたところ、住所が間違っていた。','しらべたところ、じゅうしょがまちがっていた。','Shirabeta tokoro, jūsho ga machigatte ita.','When I checked, the address was wrong.')],'調べた（　）、住所が違っていた。',['ところ','ばかり','次第','うちに'],'ところ'),
'たばかり':('have just done','Vた + ばかり',[('昼ご飯を食べたばかりです。','ひるごはんをたべたばかりです。','Hirugohan o tabeta bakari desu.','I have just eaten lunch.'),('日本に来たばかりなので、まだ慣れていない。','にほんにきたばかりなので、まだなれていない。','Nihon ni kita bakari na node, mada narete inai.','I just came to Japan, so I am not used to it yet.'),('買ったばかりの靴が汚れた。','かったばかりのくつがよごれた。','Katta bakari no kutsu ga yogoreta.','The shoes I just bought got dirty.')],'彼は日本に来（　）です。',['たばかり','ばかりだ','ところだ','ついでに'],'たばかり'),
'次第':('as soon as; depending on','V masu-stem + 次第; N + 次第',[('準備ができ次第、出発します。','じゅんびができしだい、しゅっぱつします。','Junbi ga deki shidai, shuppatsu shimasu.','We will leave as soon as preparations are ready.'),('結果が分かり次第、連絡します。','けっかがわかりしだい、れんらくします。','Kekka ga wakari shidai, renraku shimasu.','I will contact you as soon as I know the result.'),('天候次第で予定を変更する。','てんこうしだいでよていをへんこうする。','Tenkō shidai de yotei o henkō suru.','We will change the plan depending on the weather.')],'結果が分かり（　）、連絡します。',['次第','途中で','たばかり','うちに'],'次第')}
for pat,(m,f,ex,q,op,a) in V.items(): put(pat,m,f,ex,q,op,a)
p.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8')
print('patched',len(V))
