import json
from pathlib import Path
path=Path('content/grammar.json');d=json.loads(path.read_text(encoding='utf8'))
def put(p,m,f,ex,q,a):
    i=next(i for l in d['lessons'] for i in l['items'] if i['pattern']==p)
    i.update(meaning=m,formation=f,usage='Use this construction in the relationship illustrated.',register='neutral',nuance='The context determines the exact contrast or cause.',examples=[{'jp':z[0],'reading':z[1],'romaji':z[2],'en':z[3]} for z in ex],mistake='Check polarity and attachment.',comparison='Compare with nearby contrast and reason forms.',question={'prompt':q,'options':[a,'ために','以来','ばかり'],'answer':a,'explanation':'The context requires this pattern.'})
S=[
('おかげで','thanks to','N/V plain + おかげで',[('友達のおかげで合格できた。','ともだちのおかげでごうかくできた。','Tomodachi no okage de gōkaku dekita.','Thanks to my friend, I passed.'),('薬のおかげで元気になった。','くすりのおかげでげんきになった。','Kusuri no okage de genki ni natta.','Thanks to the medicine, I recovered.'),('皆さんのおかげで成功しました。','みなさんのおかげでせいこうしました。','Minasan no okage de seikō shimashita.','Thanks to everyone, it succeeded.')],'先生の（　）合格できた。','おかげで'),
('せいで','because of; due to (negative)','N/V plain + せいで',[('雨のせいで試合が中止になった。','あめのせいでしあいがちゅうしになった。','Ame no sei de shiai ga chūshi ni natta.','Because of rain, the game was canceled.'),('寝不足のせいで集中できない。','ねぶそくのせいでしゅうちゅうできない。','Nebusoku no sei de shūchū dekinai.','Because of lack of sleep, I cannot concentrate.'),('電車が遅れたせいで遅刻した。','でんしゃがおくれたせいでちこくした。','Densha ga okureta sei de chikoku shita.','I was late because the train was delayed.')],'寝不足の（　）、集中できない。','せいで'),
('からこそ','precisely because','N/V plain + からこそ',[('好きだからこそ厳しく言う。','すきだからこそきびしくいう。','Suki da kara koso kibishiku iu.','I speak strictly precisely because I care.'),('努力したからこそ成功した。','どりょくしたからこそせいこうした。','Doryoku shita kara koso seikō shita.','I succeeded precisely because I worked hard.'),('家族だからこそ本音を話せる。','かぞくだからこそほんねをはなせる。','Kazoku da kara koso honne o hanaseru.','Precisely because we are family, I can speak honestly.')],'努力した（　）成功した。','からこそ'),
('のに','although; despite','V/adj plain + のに; N/な-adj なのに',[('約束したのに来なかった。','やくそくしたのにこなかった。','Yakusoku shita noni konakatta.','Although they promised, they did not come.'),('薬を飲んだのに熱が下がらない。','くすりをのんだのにねつがさがらない。','Kusuri o nonda noni netsu ga sagaranai.','Although I took medicine, my fever is not falling.'),('静かなのに眠れない。','しずかなのにねむれない。','Shizuka na noni nemurenai.','Although it is quiet, I cannot sleep.')],'薬を飲んだ（　）、熱が下がらない。','のに'),
('けれども','but; although','V/adj plain + けれども',[('行きたいけれども時間がない。','いきたいけれどもじかんがない。','Ikitai keredomo jikan ga nai.','I want to go, but I have no time.'),('便利だけれども高い。','べんりだけれどもたかい。','Benri da keredomo takai.','It is convenient, but expensive.'),('雨が降ったけれども出かけた。','あめがふったけれどもでかけた。','Ame ga futta keredomo dekaketa.','Although it rained, I went out.')],'便利だ（　）高い。','けれども'),
('にもかかわらず','despite; regardless of','N/V plain + にもかかわらず',[('大雨にもかかわらず試合を行った。','おおあめにもかかわらずしあいをおこなった。','Ōame ni mo kakawarazu shiai o okonatta.','Despite heavy rain, they held the game.'),('注意したにもかかわらず間違えた。','ちゅういしたにもかかわらずまちがえた。','Chūi shita ni mo kakawarazu machigaeta.','Despite being careful, I made a mistake.'),('努力にもかかわらず結果が出なかった。','どりょくにもかかわらずけっかがでなかった。','Doryoku ni mo kakawarazu kekka ga denakatta.','Despite the effort, there was no result.')],'大雨（　）試合を行った。','にもかかわらず')]
for p,m,f,e,q,a in S:put(p,m,f,e,q,a)
path.write_text(json.dumps(d,ensure_ascii=False,indent=2),encoding='utf8');print('patched',len(S))
